oVirt/ovirt-ansible-collection

plugins/modules/ovirt_vm.py
Backport of https://github.com/ansible/ansible/pull/67611
=> backport of ovirt_vm numa 

plugins/modules/ovirt_vm.py
Backport https://github.com/ansible/ansible/pull/67922
=> ovirt_vm: remove deprecated warning of boot params

plugins/modules/ovirt_snapshot.py
Backport of https://github.com/ansible/ansible/pull/67815
=> ovirt_snapshot: disk id was incorrectly set as disk_snapshot_id

plugins/modules/ovirt_vm.py
Backport of https://github.com/ansible/ansible/pull/67612
=> ovirt_vm: backport of cpu_pinning example

plugins/modules/ovirt_storage_domain.py
Backport of https://github.com/ansible/ansible/pull/68187
=> ovirt_storage_domain: fix update_check warning_low_space

ovirt-ansible-collection.spec.in, plugins/doc_fragments/ovirt.py, plugins/doc_fragments/ovirt_info.py, plugins/module_utils/ovirt.py, plugins/modules/ovirt_auth.py
After this patch will be merged we can merge also https://github.com/ansible/ansible/pull/65916.
@mwperina
=> Bump SDK requirement to 4.4

plugins/modules/ovirt_datacenter.py
Hi,
this pr adds new logic to ovirt_datacenter to manage iscsi_bonds.
issue: https://bugzilla.redhat.com/show_bug.cgi?id=1613763
cc: @mwperina @sandrobonazzola @tiraboschi
=> ovirt_datacenter: add iscsi_bonds

plugins/modules/ovirt_cluster.py
Add migration_encrypted option.
After https://github.com/oVirt/ovirt-ansible-collection/pull/13 we can migrate original PR https://github.com/ansible/ansible/pull/65916.
@dangel101 @mwperina
=> Add migration_encrypted option

plugins/modules/ovirt_quota.py
=> ovirt_quota: fix vcpu_limit

plugins/modules/ovirt_disk.py
update example in ovirt_vm: change ovirt_quotas_facts ovirt_quotas_info
=> ovirt_vm: fix quotas example

plugins/modules/ovirt_template.py, plugins/modules/ovirt_vm.py, plugins/modules/ovirt_vmpool.py
False is not supported and results in an error so this should be
hard-coded to True.
Fixes #32
=> hard code nic on_boot to True

plugins/modules/ovirt_disk.py
ovirt_disk: fix upload examples
=> ovirt_disk: fix upload examples

plugins/modules/ovirt_storage_vm_info.py
This PR intends to fix https://github.com/ansible-collections/community.general/issues/462
=> Fix Incorrect Examples in ovirt_storage_vm_info

plugins/modules/ovirt_template.py, plugins/modules/ovirt_vm.py
The custom_script already works for sysprep. Add the documentation
for the same.
=> ovirt_vm: Add documentation for custom_script under sysprep

plugins/modules/ovirt_disk.py
Fixes https://github.com/oVirt/ovirt-ansible-collection/issues/56
=> ovirt_disk: add backup

plugins/modules/ovirt_host.py
=> ovirt_host: add ssh_port

README.md
=> update modules documentation link

plugins/doc_fragments/ovirt.py, plugins/doc_fragments/ovirt_info.py, plugins/inventory/ovirt.py, plugins/module_utils/ovirt.py, plugins/modules/ovirt_affinity_group.py, plugins/modules/ovirt_affinity_label.py, plugins/modules/ovirt_auth.py, plugins/modules/ovirt_cluster.py, plugins/modules/ovirt_datacenter.py, plugins/modules/ovirt_disk.py, plugins/modules/ovirt_external_provider.py, plugins/modules/ovirt_host.py, plugins/modules/ovirt_host_network.py, plugins/modules/ovirt_instance_type.py, plugins/modules/ovirt_job.py, plugins/modules/ovirt_mac_pool.py, plugins/modules/ovirt_network.py, plugins/modules/ovirt_quota.py, plugins/modules/ovirt_role.py, plugins/modules/ovirt_scheduling_policy_info.py, plugins/modules/ovirt_snapshot.py, plugins/modules/ovirt_storage_domain.py, plugins/modules/ovirt_tag.py, plugins/modules/ovirt_template.py, plugins/modules/ovirt_vm.py, plugins/modules/ovirt_vm_os_info.py, plugins/modules/ovirt_vnic_profile.py
fix docs for ansible-base 
https://github.com/oVirt/ovirt-ansible-collection/issues/74
=> fix docs for 2.10

meta/runtime.yml
add requires_ansible as in https://github.com/ansible-collections/overview/blob/master/collection_requirements.rst#metaruntimeyml
https://github.com/oVirt/ovirt-ansible-collection/issues/74
=> add requires_ansible to meta/runtime.yml

plugins/modules/ovirt_affinity_label_info.py, plugins/modules/ovirt_api_info.py, plugins/modules/ovirt_auth.py, plugins/modules/ovirt_cluster_info.py, plugins/modules/ovirt_datacenter_info.py, plugins/modules/ovirt_disk_info.py, plugins/modules/ovirt_event_info.py, plugins/modules/ovirt_external_provider_info.py, plugins/modules/ovirt_group_info.py, plugins/modules/ovirt_host_info.py, plugins/modules/ovirt_host_storage_info.py, plugins/modules/ovirt_network_info.py, plugins/modules/ovirt_nic_info.py, plugins/modules/ovirt_permission_info.py, plugins/modules/ovirt_quota_info.py, plugins/modules/ovirt_scheduling_policy_info.py, plugins/modules/ovirt_snapshot_info.py, plugins/modules/ovirt_storage_domain_info.py, plugins/modules/ovirt_storage_template_info.py, plugins/modules/ovirt_storage_vm_info.py, plugins/modules/ovirt_tag_info.py, plugins/modules/ovirt_template_info.py, plugins/modules/ovirt_user_info.py, plugins/modules/ovirt_vm.py, plugins/modules/ovirt_vm_info.py, plugins/modules/ovirt_vm_os_info.py, plugins/modules/ovirt_vmpool_info.py, plugins/modules/ovirt_vnic_profile_info.py
=> fix FQCN ansible.builtin modules

.gitignore, CHANGELOG.rst, changelogs/changelog.yaml, changelogs/config.yaml
Fix changelogs folder from now when doing some PR add info to fragments and when releasing bump galaxy version and `antsibull-changelog release` to generate logs.
#74
=> Fix changelogs

changelogs/fragments/README.md
Add fragments README.md which describes how fragment should look.
=> Add fragments README.md

automation/build-artifacts.sh
=> Add ansible-lint to CI

changelogs/fragments/add-cluster_upgrade-role.yml, roles/cluster_upgrade/README.md, roles/cluster_upgrade/defaults/main.yml, roles/cluster_upgrade/examples/cluster_upgrade.yml, roles/cluster_upgrade/examples/passwords.yml, roles/cluster_upgrade/tasks/cluster_policy.yml, roles/cluster_upgrade/tasks/main.yml, roles/cluster_upgrade/tasks/pinned_vms.yml, roles/cluster_upgrade/tasks/upgrade.yml
Migrating the cluster_upgrade role from commit: https://github.com/oVirt/ovirt-ansible-cluster-upgrade/commit/0b99cf8c388a6f68c3d0701c14d408ba8c7f58d3
=> Add role: cluster_upgrade

changelogs/fragments/add-image_template-role.yml, roles/image_template/README.md, roles/image_template/defaults/main.yml, roles/image_template/examples/ovirt_image_template.yml, roles/image_template/examples/passwords.yml, roles/image_template/tasks/empty.yml, roles/image_template/tasks/glance_image.yml, roles/image_template/tasks/main.yml, roles/image_template/tasks/qcow2_image.yml, roles/image_template/vars/main.yml
Migrating the image_template role from commit: https://github.com/oVirt/ovirt-ansible-image-template/commit/35a28036ba49d5f8f68ae5a7027060ef5a6f268a
=> Add role: image_template

changelogs/fragments/add-repositories-role.yml, roles/repositories/README.md, roles/repositories/defaults/main.yml, roles/repositories/examples/ovirt_repositories_release_rpm.yml, roles/repositories/examples/ovirt_repositories_subscription_manager.yml, roles/repositories/examples/passwords.yml, roles/repositories/tasks/backup-repos.yml, roles/repositories/tasks/main.yml, roles/repositories/tasks/rh-subscription.yml, roles/repositories/tasks/rpm.yml, roles/repositories/vars/default.yml, roles/repositories/vars/engine_4.1.yml, roles/repositories/vars/engine_4.2.yml, roles/repositories/vars/engine_4.3.yml, roles/repositories/vars/engine_4.4.yml, roles/repositories/vars/host_4.1.yml, roles/repositories/vars/host_4.2.yml, roles/repositories/vars/host_4.3.yml, roles/repositories/vars/host_4.4.yml, roles/repositories/vars/rhvh_4.1.yml, roles/repositories/vars/rhvh_4.2.yml, roles/repositories/vars/rhvh_4.3.yml, roles/repositories/vars/rhvh_4.4.yml
Migrating the repositories role from commit: https://github.com/oVirt/ovirt-ansible-repositories/commit/f032b158509e38e0729a7ec032227f9f02cca092
=> Add role: repositories

automation/build-artifacts.sh, galaxy.yml
=> Add ansible-galaxy build of collection

roles/repositories/README.md, roles/repositories/defaults/main.yml, roles/repositories/tasks/rh-subscription.yml
Sync repositories with the original role
=> Sync repositories with the original role

automation/build-artifacts.sh
=> Remove rhv build

README.md
=> remove dependencies in readme.md

changelogs/fragments/ovirt_vm-fix-template-search.yml, plugins/modules/ovirt_vm.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/100
=> ovirt_vm: fix template search

roles/hosted_engine_setup/tasks/full_execution.yml, roles/hosted_engine_setup/tasks/partial_execution.yml
=> roles: hosted_engine_setup: Use the correct FQCN

build.sh, ovirt-ansible-collection.spec.in
=> Release 1.2.0-0.1

changelogs/fragments/ovirt-inventory-add-connection-close.yml, plugins/inventory/ovirt.py
=> Backport: Add connection close at the end of inventory sync

roles/engine_setup/tasks/main.yml, roles/infra/tasks/main.yml
infra, engine_setup: remove collections
This fixes the usage of modules from inside the collection
=> infra, engine_setup: remove collections

README-developers.md, README.md
=> Update readme and add readme for devs

roles/image_template/tasks/qcow2_image.yml, roles/manageiq/tasks/deploy_qcow2.yml
C.F. https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html
=> Fix null reference when stat.isdir is not a directory. 

changelogs/fragments/ovirt_nic_info-add-template.yml, plugins/modules/ovirt_nic_info.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1884614
=> ovirt_nic_info: add template

changelogs/fragments/ovirt_nic-add-template_version.yml, plugins/modules/ovirt_nic.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1884618
=> ovirt_nic: add template_version

changelogs/fragments/engine_setup-fix-ansible-package-update.yml, roles/engine_setup/tasks/engine_setup.yml
Continuation of https://github.com/oVirt/ovirt-ansible-collection/pull/143
@mwperina
=> engine_setup: yum.conf set 'best' to false

build.sh, ovirt-ansible-collection.spec.in
=> Release 1.2.0-0.3

roles/infra/roles/aaa_jdbc/README.md, roles/infra/roles/clusters/README.md, roles/infra/roles/datacenter_cleanup/README.md, roles/infra/roles/datacenters/README.md, roles/infra/roles/datacenters/tasks/main.yml, roles/infra/roles/external_providers/README.md, roles/infra/roles/hosts/README.md, roles/infra/roles/mac_pools/README.md, roles/infra/roles/networks/README.md, roles/infra/roles/permissions/README.md, roles/infra/roles/storages/README.md, roles/infra/tasks/create_infra.yml, roles/infra/tasks/remove_infra.yml
when I try to use the infra roles I get the following error:
ERROR! the role 'infra/roles/mac_pools' was not found in ovirt.ovirt:ansible.builtin...
this PR fixing the infra roles
=> update infra roles to be able to run them

plugins/modules/ovirt_permission.py, roles/image_template/tasks/qcow2_image.yml, roles/infra/roles/hosts/tasks/main.yml, roles/manageiq/tasks/main.yml, roles/vm_infra/tasks/create_inventory.yml, roles/vm_infra/tasks/main.yml, roles/vm_infra/tasks/vm_state_present.yml
use `@NAMESPACE@.@NAME@` instead of `ovirt.ovirt`
=> Use dynamic FQCN

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/add-cluster_upgrade-role.yml, changelogs/fragments/add-disaster_recovery-role.yml, changelogs/fragments/add-engine_setup-role.yml, changelogs/fragments/add-gpl-license.yml, changelogs/fragments/add-hosted_engine_setup-role.yml, changelogs/fragments/add-image_template-role.yml, changelogs/fragments/add-infra-role.yml, changelogs/fragments/add-manageiq-role.yml, changelogs/fragments/add-repositories-role.yml, changelogs/fragments/add-shutdown_env-role.yml, changelogs/fragments/add-vm_infra-role.yml, changelogs/fragments/basic_auth-fix_create_target_hosted_engine_vm.yml, changelogs/fragments/hosted_engine_setup-add-compatibility_version.yml, changelogs/fragments/hosted_engine_setup-allow-uppercase-in-mac-address.yml, changelogs/fragments/hosted_engine_setup-set-custom-bios-type.yml, changelogs/fragments/hosted_engine_setup-use-zcat-instead-of-gzip.yml, changelogs/fragments/ovirt-inventory-add-connection-close.yml, changelogs/fragments/ovirt_disk-fix-move.yml, changelogs/fragments/ovirt_disk-fix-upload-when-direct-upload-fails.yml, changelogs/fragments/ovirt_disk-ignore-he-disk-move.yml, changelogs/fragments/ovirt_nic-add-template_version.yml, changelogs/fragments/ovirt_nic_info-add-template.yml, changelogs/fragments/ovirt_vm-fix-template-search.yml, changelogs/fragments/ovirt_vm-rename-q35_sea.yml, changelogs/fragments/ovirt_vm_info-add-current_cd.yml, galaxy.yml, ovirt-ansible-collection.spec.in
=> Release 1.2.0-1

roles/infra/roles/aaa_jdbc/tasks/main.yml
Backport of https://github.com/oVirt/ovirt-ansible-infra/pull/81
=> infra: fix Python3 support - iteritems

ovirt-ansible-collection.spec.in
We added "Obsoletes:" recently but it seems to not be enough.
=> Add "Provides:" to the packages we replace

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, ovirt-ansible-collection.spec.in
=> Release 1.2.2

roles/engine_setup/tasks/restore_engine_from_file.yml
This PR fixes CI tests from PRs which were merged but not tested properly
=> fix: ci errors

roles/infra/roles/aaa_jdbc/tasks/main.yml
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/191
=> Infra: dont require password for user

plugins/modules/ovirt_disk.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/203
=> ovirt_disk: add install warning

automation/build-artifacts.sh
Fixes testing of new modules in ansible-lint
=> Automation: add ANSIBLE_LIBRARY

plugins/modules/ovirt_host.py
ovirt_host: add reboot_after_installation
https://github.com/oVirt/ovirt-engine-api-model/commit/f7ad438bbaba32f7f84204de69c0bbb31b8735a2
=> ovirt_host: add reboot_after_installation

roles/cluster_upgrade/README.md, roles/cluster_upgrade/tasks/main.yml
Related to https://gerrit.ovirt.org/#/c/ovirt-engine/+/113210/
@mwperina
=> cluster_upgrade: Add correlation-id header

roles/engine_setup/README.md, roles/engine_setup/defaults/main.yml, roles/engine_setup/templates/answerfile_4.4_basic.txt.j2, roles/engine_setup/templates/answerfile_4.4_upgrade.txt.j2, roles/engine_setup/templates/pki_confim.txt.j2
This answer is supported by the hosted_engine_setup role
but it is not supported by engine_setup role
=> Add an answer for the PKI confirm skip question

changelogs/fragments/237-hosted_engine_setup-fix-auth_revoke.yml, roles/hosted_engine_setup/tasks/auth_revoke.yml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1940438
@arachmani @mwperina
=> hosted_engine_setup: fix auth revoke

roles/repositories/README.md, roles/repositories/vars/host_ppc_4.4.yml
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/247
=> repositories: add host ppc

plugins/modules/ovirt_vm.py
https://bugzilla.redhat.com/show_bug.cgi?id=1933238
=> ovirt_vm: allow cluster migration

roles/repositories/vars/host_ppc_4.4.yml
Fixes https://github.com/oVirt/ovirt-ansible-collection/issues/253
=> repositories: fix ppc repos

roles/hosted_engine_setup/README.md
Fixes https://github.com/oVirt/ovirt-ansible-collection/issues/257
=> role: hosted_engine_setup: Add he_force_ip4 & he_force_ip6 to README

automation/build-artifacts.packages, automation/build-artifacts.sh
automation: add ansible-test dependencies
=> automation: add ansible-test dependencies

changelogs/fragments/274-ovirt_host-update-iscsi-target-struct.yml, ovirt-ansible-collection.spec.in, plugins/modules/ovirt_host.py, requirements.txt
Follow up of https://bugzilla.redhat.com/show_bug.cgi?id=1926819
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/213
=> ovirt_host: update iscsi target struct

changelogs/fragments/282-infra-storage-fix-parameters-typo.yml, roles/infra/roles/storages/tasks/main.yml
https://github.com/oVirt/ovirt-ansible-collection/pull/252/files#r629719544
=> infra: storage fix parameters typo

changelogs/fragments/hosted_engine_setup-remove-cloud-init-config.yml, roles/hosted_engine_setup/tasks/clean_cloud_init_config.yml, roles/hosted_engine_setup/tasks/create_target_vm/02_engine_vm_configuration.yml
Remove cloud-init configuration from the engine VM
Bug-Url: https://bugzilla.redhat.com/1965456
=> roles: hosted_engine_setup: Remove cloud-init configuration

galaxy.yml
=> galaxy.yml: add tags

changelogs/fragments/297-ovirt_infra_networks-add-external-provider.yml, roles/infra/README.md, roles/infra/roles/networks/tasks/main.yml
Adding missing external_provider paramenter on ovirt_network task
of ovirt_infra
=> role: infra: networks: add external_provider var

changelogs/fragments/301-ovirt_vm-add-default-to-check_placement_policy.yml, plugins/modules/ovirt_vm.py
https://bugzilla.redhat.com/show_bug.cgi?id=1973640
=> ovirt_vm: add default to check_placement_policy

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/inventory_plugin_key_choices.yml, galaxy.yml
Custom release for automation hub
=> Release 1.4.4

changelogs/fragments/310-HE-minor-doc-update.yml, roles/hosted_engine_setup/README.md
I noticed that this is missing/inaccurate when writing:
https://bugzilla.redhat.com/show_bug.cgi?id=1932392#c23
=> roles: hosted_engine_setup: Minor doc update

changelogs/fragments/313-allow-fips-on-HE-vm.yml, roles/hosted_engine_setup/README.md, roles/hosted_engine_setup/defaults/main.yml, roles/hosted_engine_setup/tasks/apply_openscap_profile.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/03_engine_initial_tasks.yml, roles/hosted_engine_setup/tasks/get_appliance_dist.yml, roles/hosted_engine_setup/tasks/reboot_to_enable_fips.yml
Support enabling FIPS on the HE VM
Bug-Url: https://bugzilla.redhat.com/1967530
=> roles: hosted_engine_setup: Allow FIPS on HE VM

changelogs/fragments/327-pause-on-restore.yml, roles/hosted_engine_setup/README.md, roles/hosted_engine_setup/defaults/main.yml, roles/hosted_engine_setup/tasks/restore_backup.yml
Bug-Url: https://bugzilla.redhat.com/1991171
=> roles: hosted_engine_setup: Pause on failed restore

changelogs/fragments/331-use-default-bridge-for-ipv6-advertisements.yml, roles/hosted_engine_setup/tasks/alter_libvirt_default_net_configuration.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml
Bug-Url: https://bugzilla.redhat.com/1947709
=> roles: hosted_engine_setup: Use default bridge for ipv6 advertisements

changelogs/fragments/341-image_template-fix-include-tasks.yml, roles/image_template/tasks/qcow2_image.yml
The issue occurred in the EE with the latest ansible 2.12.
=> image_tempalte: Remove static false from qcow2_image

changelogs/fragments/347-ovirt_disk-add-warning-for-disk-attachemtns.yml, plugins/modules/ovirt_disk.py
https://bugzilla.redhat.com/show_bug.cgi?id=2004018
=> ovirt_disk add warning for DiskAttachments params

build.sh, galaxy.yml
=> Update master version to 1.7.0

changelogs/fragments/339-ovirt_vm-add-display-params.yml, plugins/modules/ovirt_vm.py
https://bugzilla.redhat.com/show_bug.cgi?id=1996098
=> ovirt_vm: Add display file_transfer_enabled and copy_paste_enabled

automation/build-artifacts-manual.ansible-core.repos, automation/build-artifacts-manual.ansible.repos, automation/build-artifacts.ansible-core.repos, automation/build-artifacts.ansible.repos, automation/build-artifacts.packages, automation/build-artifacts.repos, automation/check-merged.repos, automation/check-patch.ansible-core.repos, automation/check-patch.ansible.repos, changelogs/fragments/358-ovirt_disk-use-imageio-client.yml, ovirt-ansible-collection.spec.in, plugins/modules/ovirt_disk.py, requirements.txt
This PR uses the imageio client instead of direct upload to the host/proxy.
=> ovirt_disk: use imageio client

changelogs/fragments/380-hosted_engine_setup-honor-he_offline_deployment.yaml, roles/hosted_engine_setup/tasks/full_execution.yml, roles/hosted_engine_setup/tasks/install_appliance.yml, roles/hosted_engine_setup/tasks/partial_execution.yml
Honor he_offline_deployment variable.
Avoid any package update/install
when in offline mode.
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
=> roles: hosted_engine_setup: Fix offline deployment

changelogs/fragments/378-bump-deprecate-version.yml, plugins/modules/ovirt_affinity_label_info.py, plugins/modules/ovirt_cluster_info.py, plugins/modules/ovirt_datacenter_info.py, plugins/modules/ovirt_disk_info.py, plugins/modules/ovirt_event_info.py, plugins/modules/ovirt_external_provider_info.py, plugins/modules/ovirt_group_info.py, plugins/modules/ovirt_host_info.py, plugins/modules/ovirt_host_storage_info.py, plugins/modules/ovirt_network_info.py, plugins/modules/ovirt_nic_info.py, plugins/modules/ovirt_permission_info.py, plugins/modules/ovirt_quota_info.py, plugins/modules/ovirt_scheduling_policy_info.py, plugins/modules/ovirt_snapshot_info.py, plugins/modules/ovirt_storage_domain_info.py, plugins/modules/ovirt_storage_template_info.py, plugins/modules/ovirt_storage_vm_info.py, plugins/modules/ovirt_system_option_info.py, plugins/modules/ovirt_tag_info.py, plugins/modules/ovirt_template_info.py, plugins/modules/ovirt_user_info.py, plugins/modules/ovirt_vm_info.py, plugins/modules/ovirt_vm_os_info.py, plugins/modules/ovirt_vmpool_info.py, plugins/modules/ovirt_vnic_profile_info.py
info: bump deprecate version for fetch_nested and nested_attributes
=> info: bump deprecate version for fetch_nested and nested_attributes

changelogs/fragments/384-manageiq-add-deprecation-info.yaml, roles/manageiq/README.md
* manageiq: add deprecation info
* add changelog
* remove 381 changelog
* Update README.md
* Update 384-manageiq-add-deprecation-info.yaml
* Update README.md
* Update 384-manageiq-add-deprecation-info.yaml
=> backport manageiq: add deprecation info (#384)

changelogs/fragments/355-info-modules-enable-follow-parameter.yml, plugins/modules/ovirt_affinity_label_info.py, plugins/modules/ovirt_api_info.py, plugins/modules/ovirt_cluster_info.py, plugins/modules/ovirt_datacenter_info.py, plugins/modules/ovirt_disk_info.py, plugins/modules/ovirt_event_info.py, plugins/modules/ovirt_external_provider_info.py, plugins/modules/ovirt_group_info.py, plugins/modules/ovirt_host_info.py, plugins/modules/ovirt_host_storage_info.py, plugins/modules/ovirt_network_info.py, plugins/modules/ovirt_nic_info.py, plugins/modules/ovirt_permission_info.py, plugins/modules/ovirt_quota_info.py, plugins/modules/ovirt_scheduling_policy_info.py, plugins/modules/ovirt_snapshot_info.py, plugins/modules/ovirt_storage_domain_info.py, plugins/modules/ovirt_storage_template_info.py, plugins/modules/ovirt_storage_vm_info.py, plugins/modules/ovirt_system_option_info.py, plugins/modules/ovirt_tag_info.py, plugins/modules/ovirt_template_info.py, plugins/modules/ovirt_user_info.py, plugins/modules/ovirt_vm_info.py, plugins/modules/ovirt_vm_os_info.py, plugins/modules/ovirt_vmpool_info.py, plugins/modules/ovirt_vnic_profile_info.py
* info modules: enable follow parameter
* add changelogs
* update warning
=> backport info modules: enable follow parameter (#355)

changelogs/fragments/367-info-rename-follows-to-follows.yml, plugins/doc_fragments/ovirt_info.py, plugins/module_utils/ovirt.py, plugins/modules/ovirt_affinity_label_info.py, plugins/modules/ovirt_cluster_info.py, plugins/modules/ovirt_datacenter_info.py, plugins/modules/ovirt_disk_info.py, plugins/modules/ovirt_event_info.py, plugins/modules/ovirt_external_provider_info.py, plugins/modules/ovirt_group_info.py, plugins/modules/ovirt_host_info.py, plugins/modules/ovirt_host_storage_info.py, plugins/modules/ovirt_network_info.py, plugins/modules/ovirt_nic_info.py, plugins/modules/ovirt_permission_info.py, plugins/modules/ovirt_quota_info.py, plugins/modules/ovirt_scheduling_policy_info.py, plugins/modules/ovirt_snapshot_info.py, plugins/modules/ovirt_storage_domain_info.py, plugins/modules/ovirt_storage_template_info.py, plugins/modules/ovirt_storage_vm_info.py, plugins/modules/ovirt_system_option_info.py, plugins/modules/ovirt_tag_info.py, plugins/modules/ovirt_template_info.py, plugins/modules/ovirt_user_info.py, plugins/modules/ovirt_vm_info.py, plugins/modules/ovirt_vm_os_info.py, plugins/modules/ovirt_vmpool_info.py, plugins/modules/ovirt_vnic_profile_info.py
* info: Rename follows to follow parameter and add alias
* add changelogs
* fix ovirt_vm_info follow
=> Backport info: Rename follows to follow parameter and add alias (#367)

changelogs/fragments/394-hosted_engine_setup-remove-spice-graphic-protocol.yml, roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml, roles/hosted_engine_setup/templates/hosted-engine.conf.j2, roles/hosted_engine_setup/templates/vm.conf.j2
Bug-Url: https://bugzilla.redhat.com/2026770
=> roles: hosted_engine_setup: Remove SPICE from graphic protocols

build.sh, ovirt-ansible-collection.spec.in
=> Build 2.0.0 beta3

changelogs/fragments/414-prepare-for-4.5-release.yaml, roles/engine_setup/README.md, roles/engine_setup/defaults/main.yml, roles/engine_setup/examples/engine-deploy.yml, roles/engine_setup/templates/answerfile_4.5_basic.txt.j2, roles/engine_setup/templates/answerfile_4.5_upgrade.txt.j2, roles/engine_setup/tests/test-master.yml
1. Adds 4.5 answer files templates
2. Sets 4.5 as the default version for engine_setup role
=> Prepare answer files and default values for 4.5 release

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
https://help.github.com/en/articles/about-code-owners
=> Add CODEOWNERS

changelogs/fragments/423-hosted_engine_setup-fix-default-gateway-variable-name.yml, roles/hosted_engine_setup/README.md, roles/hosted_engine_setup/defaults/main.yml
=> roles: hosted_engine_setup: Fix default gateway variable name

ovirt-ansible-collection.spec.in
Remove ansible requirement for oVirt host el9 support
=> Remove ansible requirement

changelogs/fragments/436-add-json_query-filter.yml, plugins/filter/json_query.py, roles/hosted_engine_setup/tasks/bootstrap_local_vm/02_create_local_vm.yml, roles/hosted_engine_setup/tasks/create_storage_domain.yml, roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml, roles/image_template/tasks/glance_image.yml, roles/image_template/tasks/qcow2_image.yml, roles/vm_infra/tasks/vm_state_present.yml
The json_query was moved from ansible core to the `community.general` collection. For easier support, we decided to copy the `json_query` filter to the `ovirt.ovirt` collection.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2022620
=> Add json_query filter

changelogs/fragments/439-ovirt_host-add-enroll_certificate.yml, plugins/modules/ovirt_host.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/437
=> ovirt_host: Add enroll_certificate

changelogs/fragments/440-repositories-update-docs.yml, roles/repositories/README.md
Add to the documentation variable priority.
=> Update satellite docs

changelogs/fragments/444-plugins-remove_unused_imports.yml, plugins/filter/ovirtvmip.py
=> plugins: Remove unused imports

.github/workflows/build.yaml, automation/build.sh, ovirt-ansible-collection.spec.in
Continuation of https://github.com/oVirt/ovirt-ansible-collection/pull/447/
=> Switch to ci matrix

.github/workflows/build.yaml, changelogs/fragments/459-hosted_engine_setup-fix-call-to-engine-psql-for-vds_spm_id.yml, plugins/modules/ovirt_affinity_label_info.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/461
=> Fix ci check for changelog

changelogs/fragments/465-ovirt_template-add-boot_menu-and-bios_type.yml, plugins/modules/ovirt_template.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/464
=> ovirt_template: add boot_menu and bios_type

changelogs/fragments/471-make-storage-format-optional.yml, plugins/modules/ovirt_storage_domain.py
Default to None and do not fail if it's missing.
=> ovirt_storage_domain: make storage_format optional

changelogs/fragments/482-inventory-fix-url-address.yml, plugins/inventory/ovirt.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/458
=> inventory: fix url for ovirt-engine-api-model

changelogs/fragments/481-ovirt_affinity_group-add-affinity-labels.yml, plugins/modules/ovirt_affinity_group.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/479
=> ovirt_affinity_group: Add affinity labels

.github/workflows/ost.yaml
=> github: Add OST automation

changelogs/fragments/519-sync-cloud_py.yml, plugins/module_utils/cloud.py
Sync cloud.py with original https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/cloud.py
=> Sync cloud.py with origin

changelogs/fragments/521-optional-cleanup.yml, roles/hosted_engine_setup/tasks/initial_clean.yml
- hosted_engine_setup: make vdsm config cleanup optional
=> roles: hosted_engine_setup: vdsm optional

changelogs/fragments/517-engien_setup-allow-to-disable-cert-validation.yml, roles/engine_setup/README.md, roles/engine_setup/tasks/engine_setup.yml
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/494
=> engine_setup: allow to disable cert validation

changelogs/fragments/516-remove-distutils-usage.yml, plugins/module_utils/ovirt.py
Fixes part of https://github.com/oVirt/ovirt-ansible-collection/issues/495
=> Remove deprecated python package distutils

changelogs/fragments/515-add-convert_to_bytes-filter.yml, plugins/filter/convert_to_bytes.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/496
=> Add convert_to_bytes filter

changelogs/fragments/516-remove-distutils-usage.yml, plugins/module_utils/ovirt.py
Reverts oVirt/ovirt-ansible-collection#516
=> Revert "Remove deprecated python package distutils"

changelogs/fragments/524-ovirt_vm-add-wait_after_lease.yml, plugins/modules/ovirt_vm.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1930643
=> ovirt_vm: add wait_after_lease

.github/CODEOWNERS, .github/workflows/build.yaml, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/495
=> CI: add ansible-test

changelogs/fragments/508-ovirt_hosted_engine_setup-use-firewalld-command.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/05_add_host.yml
Bug-Url: https://bugzilla.redhat.com/2092229
=> roles: hosted_engine_setup: Use command instead of firewalld module

changelogs/fragments/532-cluster_upgrade-fix-starting-up-pinned-vms.yml, roles/cluster_upgrade/tasks/main.yml, roles/cluster_upgrade/tasks/upgrade.yml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2049286
=> cluster_upgrade: Fix starting up pinned vms

changelogs/fragments/550-ovirt_snapshot-add-vm_id.yml, plugins/modules/ovirt_snapshot.py
Issue: When we have multiple VMs with the same name we were not able to specify which to select.
=> ovirt_snapshot: Add vm_id

changelogs/fragments/551-ovirt_host-fix-restarted-wait-condition.yml, plugins/modules/ovirt_host.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/201
=> ovirt_host: fix restarted wait

changelogs/fragments/483-repositories-add-rhsm_environment.yml, roles/repositories/README.md, roles/repositories/tasks/install-satellite-ca.yml, roles/repositories/tasks/main.yml, roles/repositories/tasks/rh-subscription.yml, roles/repositories/tasks/satellite-subscription.yml
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/451
=> role: repositories: Add rhsm_environment and FIPS fix

changelogs/fragments/571-hosted_engine_setup-update-ansible-version-in-readme.yml, roles/hosted_engine_setup/README.md
=> hosted_engine_setup: Update ansible version in README

changelogs/fragments/578-repositories-Add-mod_auth_openidc-and-nodejs-to-dnf-modules.yml, roles/repositories/defaults/main.yml
repositories: Add mod_auth_openidc:2.3 and nodejs:14 to dnf modules
=> repositories: Add mod_auth_openidc:2.3 and nodejs:14 to dnf modules

changelogs/fragments/581-hosted_engine_setup-fix-broken-link.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
=> hosted_engine_setup: Fix ovirt-provider-ovn-driver broken link

changelogs/fragments/603-add-filter-docs.yml, plugins/filter/convert_to_bytes.yml, plugins/filter/filtervalue.yml, plugins/filter/get_network_xml_to_dict.yml, plugins/filter/get_ovf_disk_size.yml, plugins/filter/json_query.yml, plugins/filter/ovirtdiff.yml, plugins/filter/ovirtvmip.yml, plugins/filter/ovirtvmips.yml, plugins/filter/ovirtvmipsv4.yml, plugins/filter/ovirtvmipsv6.yml, plugins/filter/ovirtvmipv4.yml, plugins/filter/ovirtvmipv6.yml, plugins/filter/removesensitivevmdata.yml, roles/hosted_engine_setup/tasks/alter_libvirt_default_net_configuration.yml
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/595
=> [WIP] Filters: Add docs

changelogs/fragments/608-fix-ovirt_host-kernel_params-type.yml, plugins/modules/ovirt_host.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/606
=> ovirt_host: Fix kernel_params elemets

.github/workflows/build.yaml
=> Enable GH CI for ovirt-ansible-collection-2.y branch

changelogs/fragments/620-image_template-add-template_bios_type.yml, roles/image_template/README.md, roles/image_template/tasks/glance_image.yml, roles/image_template/tasks/qcow2_image.yml
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/619
=> image_template: Add template_bios_type

build.sh, galaxy.yml
=> Post release 2.4.0-1

.config/ansible-lint.yml, changelogs/fragments/627-remove-warn-arg.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml, roles/hosted_engine_setup/tasks/initial_clean.yml, roles/repositories/tasks/rh-subscription.yml, roles/repositories/tasks/rpm.yml, roles/repositories/tasks/satellite-subscription.yml
It's unsupported by ansible 2.14.
See also: https://github.com/ansible/ansible/pull/77411 .
=> Remove the 'warn:' argument

.github/workflows/build.yaml
=> Use RPM installation of ansible-core on EL9

ovirt-ansible-collection.spec.in
=> Support ansible-core-2.13 on EL8

.github/workflows/build.yaml
=> Use Python 3.9 on CS8 and CS9 builds

.github/workflows/build.yaml
=> Use ansible-lint 6

.github/workflows/build.yaml
- Install Python 3.8 modules
- Remove CS9 build
=> fix stable branch ci

ovirt-ansible-collection.spec.in
Add change log to release https://github.com/oVirt/ovirt-ansible-collection/pull/642
=> Add change log to release 2.4.1

build.sh, galaxy.yml
=> Post release 2.4.1-1

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/562-improve-documentation-ovirt_disk-and-disaster_recovery.yml, changelogs/fragments/607-filters-fix-ovirtvmipsv4-with-atribute-and-network.yml, changelogs/fragments/608-fix-ovirt_host-kernel_params-type.yml, changelogs/fragments/609-filterip4-fix-filter-list.yml, changelogs/fragments/610-bump-info-deprecation.yml, changelogs/fragments/620-image_template-add-template_bios_type.yml, changelogs/fragments/623-ovirt_nic-add-network_filter_parameters.yml, changelogs/fragments/624-cluster_upgrade-add-default-random-uuid-to-engine_correlation_id.yml, changelogs/fragments/627-remove-warn-arg.yml, changelogs/fragments/637-cluster_upgrade-fix-the-engine_correlation_id-location.yml, ovirt-ansible-collection.spec.in
=> Release 3.0.0

build.sh, galaxy.yml
=> Post release 3.0.0-1

.github/workflows/build.yaml
=> Use latest versions of oVirt actions

roles/cluster_upgrade/tasks/log_progress.yml, roles/cluster_upgrade/tasks/upgrade.yml, roles/engine_setup/tasks/engine_setup.yml, roles/hosted_engine_setup/tasks/add_engine_as_ansible_host.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/02_create_local_vm.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/03_engine_initial_tasks.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/04_engine_final_tasks.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/05_add_host.yml, roles/hosted_engine_setup/tasks/clean_local_storage_pools.yml, roles/hosted_engine_setup/tasks/create_storage_domain.yml, roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml, roles/hosted_engine_setup/tasks/create_target_vm/02_engine_vm_configuration.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml, roles/hosted_engine_setup/tasks/final_clean.yml, roles/hosted_engine_setup/tasks/initial_clean.yml, roles/hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml, roles/hosted_engine_setup/tasks/pre_checks/define_variables.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_data_center_name.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_firewalld.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_gateway.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_mac_address.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_memory_size.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_network_test.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_vcpus_count.yml
Fixes block indentation issues, where a content of a block should always
be indented by 4 characters.
=> Fix latest ansible-lint issues around block indentation

roles/cluster_upgrade/tasks/log_progress.yml, roles/cluster_upgrade/tasks/upgrade.yml, roles/engine_setup/tasks/engine_setup.yml, roles/hosted_engine_setup/tasks/add_engine_as_ansible_host.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/02_create_local_vm.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/03_engine_initial_tasks.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/04_engine_final_tasks.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/05_add_host.yml, roles/hosted_engine_setup/tasks/clean_local_storage_pools.yml, roles/hosted_engine_setup/tasks/create_storage_domain.yml, roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml, roles/hosted_engine_setup/tasks/create_target_vm/02_engine_vm_configuration.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml, roles/hosted_engine_setup/tasks/final_clean.yml, roles/hosted_engine_setup/tasks/initial_clean.yml, roles/hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml, roles/hosted_engine_setup/tasks/pre_checks/define_variables.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_data_center_name.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_firewalld.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_gateway.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_mac_address.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_memory_size.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_network_test.yml, roles/hosted_engine_setup/tasks/pre_checks/validate_vcpus_count.yml
Fixes block indentation issues, where a content of a block should always
be indented by 4 characters.
=> backport: Fix latest ansible-lint issues around block indentation

changelogs/fragments/621-wait-for-host-to-be-in-result-state.yml
=> Add missing changelog for #621

changelogs/fragments/673-ovirt_host-add-refresh.yml, plugins/modules/ovirt_host.py
Fixes https://github.com/oVirt/ovirt-ansible-collection/discussions/672
=> ovirt_host: Add refresh

changelogs/fragments/684-ovirt_cluster_info-fix-example-patter.yml, plugins/modules/ovirt_cluster_info.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/683
=> ovirt_cluster_info: Fix example patter

changelogs/fragments/687-ovirt_host-fix-refreshed-state-action.yml, plugins/modules/ovirt_host.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/686
=> ovirt_host: Fix refreshed state action

build.sh, ovirt-ansible-collection.spec.in
Add Python 3.11 subpackage to be usable in ansible-core 2.14 for el8
=> Release 3.1.2-1

changelogs/fragments/704-drop-netaddr3.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
Signed-off-by: Michal Skrivanek <michal.skrivanek@redhat.com>
=> fix ipv4 and ipv6 netaddr check

changelogs/fragments/712-ovirt_quota-fix-storage-size-typecast.yml, plugins/modules/ovirt_quota.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/709
=> ovirt_quota: Convert storage size to integer

changelogs/fragments/712-ovirt_quota-fix-storage-size-typecast.yml, plugins/modules/ovirt_quota.py
Backport https://github.com/oVirt/ovirt-ansible-collection/pull/712 to ovirt-ansible-collection-2.y.
=> Backport: ovirt_quota: Convert storage size to integer

changelogs/fragments/723-ovirt_role-fix-administrative-condition.yml, plugins/modules/ovirt_role.py
Backport https://github.com/oVirt/ovirt-ansible-collection/pull/723 to ovirt-ansible-collection-2.y.
=> Backport: ovirt_role: Fix administrative option when set to False

.github/workflows/build.yaml
=> ovirt-ansible-collection-2.y CI: Disable ansible sanity tests

plugins/test/ovirt_proxied_check.py
=> Add correct documentation string for ovirt_proxied_check

examples/filters/vmips.yml
Fix unique names lint error in example.
=> lint: fix unique names
