oVirt/ovirt-ansible-collection

plugins/inventory/ovirt.py
Improve oVirt dynamic inventory plugin based on comments in https://github.com/ansible/ansible/pull/49085
- Feature Pull Request
=> ovirt dynamic plugin improvements

plugins/inventory/ovirt.py
This is a common issue that several collections hit.
Basically, if you don't use the fully qualified name here, there's no way to use this inventory because Ansible core expects it under the collection name.namespace.
I can't yet say that I've tested this, and I don't think I'll get full validation, but I'll try to check back after I manually test and make sure that with an invalid server, it gives the error I would expect.
=> Use fully qualified name in inventory plugin

plugins/modules/ovirt_template.py
Currently some of the examples don't work as they miss the vm
parameter meaning the task fails with: "Input validation failed.".
Fault detail is "No matching signature found, make sure that
mandatory attributes are provided.". HTTP response code is 400."
This commit adds the vm parameter which allows the task to
successfully complete and create a template.
=> Adds missing vm parameter to examples

plugins/modules/ovirt_instance_type.py, plugins/modules/ovirt_template.py, plugins/modules/ovirt_vm.py
Updates various modules with the current (4.4) list.
other_linux_kernel_4
other_linux_s390x
other_s390x
rhcos_x64
rhel_3x64
rhel_6_9_plus_ppc64
rhel_7_s390x
rhel_8x64
rhel_atomic7x64
sles_12_s390x
ubuntu_16_04_s390x
windows_2016x64
windows_2019x64
Removed (incorrect and duplicate):
windows_2008r2x64
=> Update operating system options

plugins/modules/ovirt_network.py
Usually, to remove some parameter we specify the variable as an empty string. 
The vlan_tag is specified as int so I have added option to remove the VLAN tag when you use -1. 
Because this is not RFE will try to push it to ansible 2.9.z.
Fixes https://github.com/oVirt/ovirt-ansible-collection/issues/20
=> ovirt_network: add support of removing vlan_tag

plugins/modules/ovirt_disk.py, tests/sanity/ignore-2.9.txt
Add warning when uploading iso and the format is cow, before this PR the upload would end on FINALIZING_FAILURE and no more information, now it shows warning which will inform the user to update to raw.
@mwperina  @dangel101
=> ovirt_disk: add upload image warning for correct format

plugins/module_utils/ovirt.py, plugins/modules/ovirt_instance_type.py, plugins/modules/ovirt_template.py, plugins/modules/ovirt_vm.py, plugins/modules/ovirt_vm_os_info.py
Add ovirt_vm_os_info as suggested in https://github.com/oVirt/ovirt-ansible-collection/pull/24
Not sure if this is the best use case, but still wanted to add the PR where we could discuss it.
Right now the module return list of dictionaries which have attributes like name, architecture etc. in [1].
When I tried to get a list of all supported OS names it was so large list with all attributes that I did have to add filter_keys to filter the output. For example, the `large_icon` and `small_icon` attributes are unnecessary for ansible (you can check them in [1] or /ovirt-engine/api/operatingsystems).
To specific attributes like a name (you can check examples). 
example of the output
```
"ovirt_vm_os": [
{
"architecture": "x86_64",
"description": "Other OS",
"href": …
```
=> Add ovirt_vm_os_info

plugins/modules/ovirt_disk.py
This is a feature when user does not specify disk size when uploading the disk. 
It will be automatically determined for him.
@mwperina  @dangel101
=> ovirt_disk: upload_image_path autodetect size

plugins/inventory/ovirt.py
add `creation_time` to ovirt inventory
=> ovirt inventory add creation_time

plugins/inventory/ovirt.py
Tested locally by doing things like:
```yaml
plugin: ovirt.ovirt.ovirt
ovirt_hostname_preference:
- name
- fqdn
strict: true
compose:
ansible_host: '(devices.values() | list)[0][0] if devices else None'
foobar: 'sefe or esfes'
```
so then it fails because "foobar" is nonsense, then
```yaml
plugin: ovirt.ovirt.ovirt
ovirt_hostname_preference:
- name
- fqdn
strict: false
compose:
ansible_host: '(devices.values() | list)[0][0] if devices else None'
foobar: 'sefe or esfes'
```
works fine, because it ignores the nonsense entry.
This is also a pretty standard pattern in other inventory plugins. It's already in the options, because it comes from the constructed doc fragment.
=> Respect constructed strict option

plugins/modules/ovirt_disk.py
Force `wait` parameter to `True` when creating a disk to which will be image uploaded.
Fixes https://github.com/oVirt/ovirt-ansible-collection/issues/28
https://github.com/ansible/ansible/issues/68487
@dangel101 @mwperina
=> ovirt_disk: force wait when uploading disk

plugins/modules/ovirt_disk.py
Fixes #29 and therefore fixes image down-/upload on oVirt 4.4 engines also see [RHBZ 1801710](https://bugzilla.redhat.com/show_bug.cgi?id=1801710).
I verified this code with the following testing playbook:
```
---                                                                                                                                                                                                                                                                                                                   
- hosts: localhost
connection: local                   
gather_facts: False
collections:
- ovirt.ovirt
tasks:
- ovirt_auth:
url: https://ovirt.example.com/ovirt-engine/api
username: admin@internal
password: password
- ovirt_disk:
auth: '{{ ovirt_auth }}'
name: testdisk
size: …
```
=> Support direct upload/download to Image I/O daemon on oVirt node

plugins/modules/ovirt_vm.py
Issues were that in the examples is shown that the `cd_iso` works with the name of the disk but it didn't and accepted only IDs. 
This fix allows both usages ID/name.
If user specifies the disk name and there are multiple disks with the same name it will fail with proper message.  
=> ovirt_vm: fix cd_iso search by name

plugins/modules/ovirt_disk.py
Issue: was not able to attach the deactivated disk to the VM
This keeps previous logic the same (default is activated) but when specifying the value it will overwrite it.
=> ovirt_disk: fix activate

plugins/inventory/ovirt.py
In Tower 3.7, I was running into an issue with a self signed certificate on my RHV cluster. Disabling secure connections when the cafile is not defined fixes this issue, in the same way that it worked in previous versions of Tower with the ovirt4 inventory plugin.
=> Set inventory plugin insecure if no cafile defined

plugins/modules/ovirt_host_network.py
the issue occurred in infra role when not specified custom_properties it failed with error not able to iterate through None
=> ovirt_host_network: fix custom_properties default value

plugins/modules/ovirt_vm.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/62
Issue: in 4.3 the disks from ISO storage domain were not able to get from disks_service to make it backward compatible did need to gather all storage domains
=> ovirt_vm: fix cd_iso get all disks from storage domains

changelogs/changelog.yaml, changelogs/fragments/ovirt_vm-rename-q35_sea.yml, plugins/modules/ovirt_vm.py
To be aligned with the oVirt's API
Signed-off-by: Arik Hadas <ahadas@redhat.com>
=> Rename q35_sea to q35_sea_bios

changelogs/fragments/ovirt-inventory-add-connection-close.yml, plugins/inventory/ovirt.py
During our usage of Ansible Tower and Inventory Sync operations against RHV we saw following:
```
1- We do inv sync frequently
2- Our RHV had sessions timeout after an hour
3- so it held onto all connections in the db and JVM (java )
4- connections pile up
```
This connection piling up is not good for environment as it uses resources unnecessarily. 
It is important we close out connection at the end.
Close the connection at the end of sync.
=> Add connection close at the end of inventory sync

changelogs/fragments/ovirt_disk-fix-upload-when-direct-upload-fails.yml, plugins/modules/ovirt_disk.py
There were multiple possible exceptions when trying to connect to the engine for direct upload to the host.
This fixes the issue and solves any other unexpected errors.
https://bugzilla.redhat.com/show_bug.cgi?id=1879165
=> ovirt_disk: fix upload when direct upload fails

changelogs/fragments/hosted_engine_setup-add-compatibility_version.yml, roles/hosted_engine_setup/README.md, roles/hosted_engine_setup/tasks/bootstrap_local_vm/05_add_host.yml
in the latest version of 4.4, we have a new data center and cluster compatibility version - 4.5
by default, we use the latest data center and cluster compatibility version - 4.5
but we need also the option to define the hosted engine to stay with compatibility version 4.4
=> added the option to set different compatibility version for data center and for cluster

changelogs/fragments/basic_auth-fix_create_target_hosted_engine_vm.yml, roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml
Force basic authentication when request server CPU list and emulated machine list via REST API. This is needed cause when restoring an engine from backup, where aaa-authentication was configured, the task will fail cause the REST API call will try to negotiate.
=> Force Basic Auth for REST API calls

changelogs/fragments/hosted_engine_setup-set-custom-bios-type.yml, roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml
To prevent its bios type from changing when the cluster's bios type changes
Bug-Url: https://bugzilla.redhat.com/1871694
Signed-off-by: Arik Hadas <ahadas@redhat.com>
=> Set hosted-engine VM with custom bios type (Q35+SeaBIOS)

changelogs/fragments/hosted_engine_setup-use-zcat-instead-of-gzip.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/02_create_local_vm.yml
Use zcat instead of gzip to check the size of the appliance
gzip reports incorrect uncompressed sizes for large files
Bug-Url: https://bugzilla.redhat.com/1821425
=> roles: hosted_engine_setup: Use zcat instead of gzip

changelogs/fragments/ovirt_disk-fix-move.yml, plugins/modules/ovirt_disk.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1883817
@mwperina @arachmani
=> ovirt_disk: dont move disk when already in storage_domain

roles/repositories/README.md, roles/repositories/defaults/main.yml, roles/repositories/tasks/rpm.yml
The `disable_gpg_check` was added because of the master rpm are not signed by the gpg key
@mwperina
=> repositories: fix gpg key

changelogs/fragments/ovirt_vm_info-add-current_cd.yml, plugins/modules/ovirt_vm_info.py
This PR adds usage of `current_cd` to the ovirt_vm_info. 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1885542 
Potential outputs:
when VM does not have any current_cd
```
"current_cd": {
"href": "/ovirt-engine/api/vms/293e855c-4477-41d3-959b-47e39ee120e4/cdroms/00000000-0000-0000-0000-000000000000",
"id": "00000000-0000-0000-0000-000000000000",
"vm": {
"href": "/ovirt-engine/api/vms/293e855c-4477-41d3-959b-47e39ee120e4",
"id": "293e855c-4477-41d3-959b-47e39ee120e4"
}
},
```
when `current_cd` is disabled
```
"current_cd": {},
```
when VM does have current_cd
```
"current_cd": {
"file": {
"id": "CentOS-8.2.2004-x86_64-minimal.iso"
},
"href": "/ovirt-engine/api/vms/52b02ec8-95ba-4f2f-b6bb-4de2fd283fa2/cdroms/00000000-0000-0000-0000-000000000000",
"id": …
```
=> ovirt_vm_info: add current_cd

automation/build-artifacts.sh, build.sh
maybe it will be better to use the BUILD_PATH as a base path (where all collections should located).
the same as:
ANSIBLE_COLLECTIONS_PATH
and add the following line to build script: 
BUILD_PATH=$BUILD_PATH/ansible_collections/ovirt/ovirt/ 
instead of everyone add it in his build command.
the build command will look like:
./build.sh build ovirt "$ANSIBLE_COLLECTIONS_PATH"
=> fix the build path to copy all files into correct path

changelogs/fragments/hosted_engine_setup-allow-uppercase-in-mac-address.yml, roles/hosted_engine_setup/templates/network-config-dhcp.j2
Change uppercase to lowercase in mac address in order to fit
cloud-init format.
Currently, When using uppercase in mac address cloud-init fails
to change the nic name to eth0 during HE deployment.
This PR should fix it.
Bug-Url: https://bugzilla.redhat.com/1850028
=> hosted_engine_setup: Allow uppercase characters in the HE-VM MAC address

plugins/modules/ovirt_host_network.py
This is a workaround to allow save until the fixed in the engine.
Proper fixed should be in https://bugzilla.redhat.com/show_bug.cgi?id=1798818
https://github.com/ansible/ansible/issues/67810
@dangel101 @mwperina
=> ovirt_host_network: fix save of network config

plugins/modules/ovirt_disk.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1883817
ignore moving of hosted engine disks
=> ovirt_disk: ignore moving of hosted engine disks

ovirt-ansible-collection.spec.in
Add Obsoletes directive to allow smooth upgrade from old standalone roles packages to the new collection package
=> Obsolete old standalone roles packages

roles/hosted_engine_setup/tasks/add_engine_as_ansible_host.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/02_create_local_vm.yml, roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml, roles/hosted_engine_setup/tasks/partial_execution.yml, roles/hosted_engine_setup/tasks/sync_on_engine_machine.yml
This is an addition to [1], missing there, updating also
partial_execution.yml . That said:
- This does not (usually?) reproduce on CI, perhaps simply because we
run there with low memory (thus forcing the kernel to sync often)
- I do not know well which parts of this code run on the host, which on
the engine, and what and when adds the engine to the inventory, so not
sure it would always work.
Copying the commit message from [1]:
Sometimes, on failed deploy attempts, engine-logs* directories are
created but left empty. I am guessing that this might be because the
files there are still cached in memory, and we do not fetch from the
engine vm itself (using e.g. ssh) but from the host, directly accessing
the vm disk image. So if, before that, we run 'sync' on the engine vm,
we have better …
=> roles: hosted_engine_setup: Improve engine logs fetching

changelogs/fragments/disaster_recovery-fix-configuration-issues.yml, roles/disaster_recovery/README.md, roles/disaster_recovery/files/dr.conf, roles/disaster_recovery/files/fail_back.py, roles/disaster_recovery/files/fail_over.py, roles/disaster_recovery/files/generate_vars.py, roles/disaster_recovery/files/validator.py
The DR project was added to the "ovirt-ansible-collection" repository and merged in
#134
This PR fixes a few small issues with it.
Signed-off-by: Pavel Bar <pbar@redhat.com>
=> Disaster Recovery fixes after added to collections

roles/repositories/README.md, roles/repositories/defaults/main.yml, roles/repositories/tasks/rpm.yml
disable_gpg_check was limited to the following condition:
if 'master.rpm' in ovirt_repositories_ovirt_release_rpm
=> add ovirt_repositories_disable_gpg_check to repositories param

roles/hosted_engine_setup/tasks/initial_clean.yml
Clean leftovers of VNC encryption config
from /etc/libvirt/qemu.conf file
Bug-Url: https://bugzilla.redhat.com/1884599
=> roles: hosted_engine_setup: Clean VNC encryption config

plugins/inventory/ovirt.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/172
Example of output: 
```
"creation_time_timestamp": "1598263100.532000",
```
Test on python2:
```python
>>> datetime.datetime.now().strftime("%s.%f")
'1604486628.612790'
```
=> Inventory plugin: fix timestamp for python2

roles/engine_setup/tasks/restore_engine_from_file.yml, roles/engine_setup/vars/main.yml
when running restore flow we failed with the following error:
TASK [ovirt.ovirt.engine_setup : Restore engine from file] *********************
fatal: [example.com]: FAILED! => {"reason": "Could not find or access
'/path/to/file/restore_engine_from_file.yml' on the Ansible Controller."}
=> Missing restore task file and vars file

roles/hosted_engine_setup/README.md, roles/hosted_engine_setup/defaults/main.yml, roles/hosted_engine_setup/examples/required_networks_fix.yml, roles/hosted_engine_setup/hooks/after_add_host/README.md, roles/hosted_engine_setup/tasks/bootstrap_local_vm/05_add_host.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml, roles/hosted_engine_setup/tasks/filter_team_devices.yml
Allow running custom playbooks after trying to add the host to the
engine.
Bug-Url: https://bugzilla.redhat.com/1893385
=> roles: hosted_engine_setup: Add after_add_host hook

plugins/inventory/ovirt.py
Fixes https://github.com/oVirt/ovirt-ansible-collection/issues/193
The return of the inventory has os_type inside even if we don't use the variable in search.
This breaks bp not sure if we should implement it.
=> correct name of os_type

roles/hosted_engine_setup/tasks/fetch_engine_logs.yml
In the code collecting stuff from the engine machine, we collect only
/var/log/messages and /var/log/ovirt-engine.
Change this to collect all of /var/log.
I think this is useful in general, and does not add too much waste (in
deploy time and space after that).
For now, I am pushing this to try to debug:
https://bugzilla.redhat.com/1915329
=> roles: hosted_engine_setup: Collect all engine /var/log

plugins/modules/ovirt_system_option_info.py, plugins/modules/ovirt_system_options_info.py
Fixes https://github.com/oVirt/ovirt-ansible-collection/issues/204
- Add new module ovirt_system_option_info to gather information about the system options.
- We cannot list the options so there are some parameters that will not be used like fetch_nested and nested_attributes. The reason why I kept it there is that I would need to 
- either create another doc fragment for this specific module and don't use the info fragment
- or move all necessary arguments to this module but this could break something if we would change the main and we could forget about this
Example input:
```yaml
ovirt.ovirt.ovirt_system_option_info:
auth: "{{ ovirt_auth }}"
name: ServerCPUList
version: "4.4"
```
Example output: 
```json
"ovirt_system_option": {
"href": "/ovirt-engine/api/options/ServerCPUList",
"id": …
```
=> Add ovirt_system_option_info

plugins/doc_fragments/ovirt_info.py
All info modules were missing the suboptions in docs.
=> ovirt_info fragment add auth suboptions docs

roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml
Get server CPU list and cluster emulated machine list using
ovirt_system_option_info module instead of using REST API
Bug-Url: https://bugzilla.redhat.com/1915286
=> roles: hosted_engine_setup: Use ovirt_system_option_info instead of REST API

automation/build-artifacts.sh, roles/hosted_engine_setup/tasks/bootstrap_local_vm/05_add_host.yml
We recently changed the host-deploy process to reboot the host after
installation. We need to revert that for hosted-engine deploy, as this
reboots the host we deploy on, thus killing the deployment.
=> roles: hosted_engine_setup: Do not reboot the host during deploy

automation/build-artifacts.sh
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/219
In ansible-lint 5.0.0 is an issue so we will not yet use it.
=> CI: specify max version ansible-lint

plugins/modules/ovirt_disk.py, plugins/modules/ovirt_host_storage_info.py
We don't need to login to iscsi before getting all information about the host storages.
Now user can only select the host from which to get the storages and filter if iscsi or fcp.
**Examples:** 
To get all storage from host:
```
- ovirt.ovirt.ovirt_host_storage_info:
host: host_mixed_1
auth: "{{ ovirt_auth }}"
```
To get only iscsi storages: 
```
- ovirt.ovirt.ovirt_host_storage_info:
host: host_mixed_1
iscsi: {}
auth: "{{ ovirt_auth }}"
```
=> ovirt_host_storage_info: no need for login to get info

changelogs/fragments/auth_dict.yml, plugins/module_utils/ovirt.py
Currently the `auth` option is a free form dict with some env fallback options. This is problematic because there is no validation happening on the user input leading to bad UX when dealing with typos or just understanding what options are available when running with `-vvv`. It will also expose the value of `password` and `token` if they are defined as an Ansible option which is not a good thing. This PR defines the `auth` sub options as part of the argument spec so `basic.py` validates the options and it still includes the env var fallbacks if not explicitly set in the task.
This should be backported to Ansible 2.9 if possible.
Fixes https://github.com/oVirt/ovirt-ansible-collection/issues/198
=> Spec auth options

plugins/doc_fragments/ovirt.py, plugins/doc_fragments/ovirt_info.py, plugins/module_utils/ovirt.py
Follow up of https://github.com/oVirt/ovirt-ansible-collection/pull/211
The issue was that the `ovirt_auth` module was returning and passing `timeout` and `compress` to other modules with the `auth` option. But they were not mentioned in the updated code which forces to match the `auth` before the #211 the options were ignored. 
@mwperina @didib
=> ovirt_auth: fix env auth dict

plugins/modules/ovirt_disk.py
Adding support for SATA interface in ovirt_disk for q35.
=> ovirt_disk: Add SATA support

roles/hosted_engine_setup/tasks/filter_unsupported_devices.yml, roles/hosted_engine_setup/tasks/filter_unsupported_vlan_devices.yml, roles/hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml
Filter VLAN devices with bond parent configured with unsupported bond mode
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1585462
Signed-off-by: Aviv Turgeman <aturgema@redhat.com>
=> role: hosted_engine_setup: Filter devices with unsupported bond mode

examples/remove_mpath_device.yml
To remove cleanly LUN from a hosts, one has to:
1. stop unsing it in oVirt (e.g. remove SD on top of this LUN)
2. unzone the LUN from storage server
3. remove multipath device for unzoned LUN from the hosts
As point 2. cannot be done oVirt, oVirt itself cannot automate whole
flow. This ansible recipe automates taks which needs to be done for
point 3. It cleanly removes multipath device which is not used any more.
Example usage:
ansible-playbook  -i hosts --extra-vars "lun=36001405042dd41f40334273abc579952" remove_mpath_device.yml
Extra parameter `lun` which is passed to the recipe is WWID of the LUN
as reported e.g. by `multipath -l`.
Bug-Url: https://bugzilla.redhat.com/1310330
=> examples: add recipe for removing DM device

plugins/modules/ovirt_user.py
https://bugzilla.redhat.com/show_bug.cgi?id=1928788
=> ovirt_user: add ssh_public_key

roles/repositories/vars/engine_4.4.yml, roles/repositories/vars/host_4.4.yml
As mentioned in https://bugzilla.redhat.com/1917409 from RHV 4.4.5
required ansible version is provided by RHV channels, so specific
ansible channel is no longer needed on RHV manager no RHV hosts.
=> Remove ansible channels from RHV 4.4

roles/hosted_engine_setup/tasks/apply_openscap_profile.yml
Use Setup module in order to fetch ansible distribution from the appliance
Bug-Url: https://bugzilla.redhat.com/1948274
=> role: hosted_engine_setup: Get the appliance distribution in a correct way

roles/hosted_engine_setup/tasks/apply_openscap_profile.yml
Add an error message when using FIPS mode on an appliance based on CentOS
in case the FIPS mode cannot be applied.
Bug-Url: https://bugzilla.redhat.com/1924590
=> role: hosted_engine_setup: Add an error message for FIPS on CentOS

roles/infra/roles/storages/tasks/main.yml
The reason for this is that the storage domain connection can be created with multiple targets, the issue comes when there is another connection with a different target than the user has specified by the storage in the YAML file.
https://bugzilla.redhat.com/show_bug.cgi?id=1943221
=> infra: remove target from ovirt_storage_connection

changelogs/fragments/hosted_engine_setup-add-pause-option-before-engine-setup.yml, roles/hosted_engine_setup/README.md, roles/hosted_engine_setup/defaults/main.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/03_engine_initial_tasks.yml
Add the option to pause the deployment and adjust changes in the
bootstrap engine VM before running the engine-setup
Bug-Url: https://bugzilla.redhat.com/1959273
=> roles: hosted_engine_setup: Add pause option before running engine-setup

automation/build-artifacts.sh
To make it easier to find what failed the build.
=> automation: Add "ERROR:" to "Please add changelog"

changelogs/fragments/hosted_engine_setup-use-ovirt_host-module-to-discover-iscsi.yml, roles/hosted_engine_setup/tasks/iscsi_discover.yml
Use `ovirt_host` module to discover iSCSI
instead of using REST API.
Requires a change in ovirt-hosted-engine-setup and cockpit-ovirt
Bug-Url: https://bugzilla.redhat.com/1922748
=> role: hosted_engine_setup: Use ovirt_host module

automation/build-artifacts.sh, plugins/doc_fragments/ovirt_info.py, plugins/module_utils/ovirt.py, plugins/modules/ovirt_affinity_label_info.py, plugins/modules/ovirt_api_info.py, plugins/modules/ovirt_cluster_info.py, plugins/modules/ovirt_datacenter_info.py, plugins/modules/ovirt_disk_info.py, plugins/modules/ovirt_event_info.py, plugins/modules/ovirt_external_provider_info.py, plugins/modules/ovirt_group_info.py, plugins/modules/ovirt_host_info.py, plugins/modules/ovirt_host_storage_info.py, plugins/modules/ovirt_network_info.py, plugins/modules/ovirt_nic_info.py, plugins/modules/ovirt_permission_info.py, plugins/modules/ovirt_quota_info.py, plugins/modules/ovirt_scheduling_policy_info.py, plugins/modules/ovirt_snapshot_info.py, plugins/modules/ovirt_storage_domain_info.py, plugins/modules/ovirt_storage_template_info.py, plugins/modules/ovirt_storage_vm_info.py, plugins/modules/ovirt_system_option_info.py, plugins/modules/ovirt_tag_info.py, plugins/modules/ovirt_template_info.py, plugins/modules/ovirt_user_info.py, plugins/modules/ovirt_vm_info.py, plugins/modules/ovirt_vm_os_info.py, plugins/modules/ovirt_vmpool_info.py, plugins/modules/ovirt_vnic_profile_info.py
We have multiple issues with the info modules.
1. the `get_dict_of_struct` function uses `connection.follow_link` which creates a request for each nested parameter and this slows the gathering of data. Using the `follow` in `list` speeds this process us because we leave it up to the engine and get all required data in one request.
2. We filter all nested data even if it was passed in the request. Now it shows exactly the same resp as in the API. (Could resolve issue https://github.com/oVirt/ovirt-ansible-collection/issues/246)
=> info modules: add follow parameter

changelogs/fragments/hosted_engine_setup-remove-leftovers-code.yml, roles/hosted_engine_setup/tasks/iscsi_discover.yml
* Remove leftover code
* Omit username and password parameters for iscsi discovery
Bug-Url: https://bugzilla.redhat.com/1922748
=> roles: hosted_engine_setup: Remove leftover code and omit parameters

changelogs/fragments/286-dr-change-conf-paths.yml, roles/disaster_recovery/files/dr.conf
Issue: When installing only from RPM the paths which were in the `dr.conf` were missing so after the DR started it created the paths and it blocked the usage of the collection because the `~/.ansible` path has higher priority than the `/usr/share/ansible`
https://bugzilla.redhat.com/show_bug.cgi?id=1965228
=> DR: change conf paths

changelogs/fragments/hosted_engine_setup-add-host-use_IP.yml, roles/hosted_engine_setup/tasks/add_engine_as_ansible_host.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/02_create_local_vm.yml, roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml
Do not rely on adding a line to /etc/hosts, as this seems to not be
enough sometimes. Instead, directly tell ansible to use the IP address.
Bug-Url: https://bugzilla.redhat.com/1953029
=>  role: hosted_engine_setup: add_host: Use local_vm_ip

changelogs/fragments/inventory_plugin_key_choices.yml, plugins/inventory/ovirt.py
Testing with the collection from Automation Hub
```
[WARNING]:  * Failed to parse /runner/inventory/ovirt.yml with auto plugin:
Invalid value "redhat.rhv.ovirt" for configuration option "plugin_type:
inventory plugin: ansible_collections.redhat.rhv.plugins.inventory.ovirt
setting: plugin ", valid values are: ['ovirt']
File "/usr/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
plugin.parse(self._inventory, self._loader, source, cache=cache)
File "/usr/lib/python3.8/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
plugin.parse(inventory, loader, path, cache=cache)
File "/usr/share/ansible/collections/ansible_collections/redhat/rhv/plugins/inventory/ovirt.py", line 238, in parse
config = self._read_config_data(path)
File …
```
=> Allow downstream name for inventory plugin

changelogs/fragments/294-ovirt_vm-add-placement_policy_dict.yml, changelogs/fragments/294-ovirt_vm-add-placement_policy_hosts.yml, plugins/modules/ovirt_vm.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1969855
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/200
=> ovirt_vm: add placement_policy_hosts

changelogs/fragments/311-fix-add-host-target-vm.yml, roles/hosted_engine_setup/tasks/add_engine_as_ansible_host.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/02_create_local_vm.yml, roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml, roles/hosted_engine_setup/tasks/sync_on_engine_machine.yml
Allow custom hooks that want to access the engine VM as an ansible host
to work also after it is started as the target public machine.
=> role: hosted_engine_setup: Fix engine vm add_host for the target machine

changelogs/fragments/307-safe-eval-no-concat.yml, roles/disaster_recovery/tasks/recover/register_vms.yml, roles/disaster_recovery/tasks/recover_engine.yml, roles/disaster_recovery/tasks/unregister_entities.yml
Don't rely on `safe_eval` being able to do math/concat. This functionality will be removed in ansible-core 2.12, and has never worked with jinja2 native which we are working toward making the default in 2.12.
See https://github.com/ansible/ansible/pull/75068
=> Don't rely on safe_eval being able to do math/concat

changelogs/fragments/314-remove-duplicate-tasks.yml, roles/hosted_engine_setup/tasks/partial_execution.yml
When using `hosted-engine --deploy`, "Sync on engine machine" and
"Final clean" tasks run twice, once at the end of "Creating Target VM" stage
and right after that in "Cleaning temporary resources" stage.
This PR removes these tasks from "Creating Target VM" stage,
therefore they will be executed only in the "Final clean" stage.
Bug-Url: https://bugzilla.redhat.com/1977486
=> roles: hosted_engine_setup: remove duplicate tasks

changelogs/fragments/315-use-forward-netrok-during-ipv6-deployment.yml, roles/hosted_engine_setup/tasks/alter_libvirt_default_net_configuration.yml
Use forward network instead of isolated network
during an IPv6 deployment
Bug-Url: https://bugzilla.redhat.com/1947709
=> roles: hosted_engine_setup: Use forward network during an IPv6 deployment

changelogs/fragments/318-ovirt_permission-fix-group-search-that-has-space.yml, plugins/modules/ovirt_permission.py
Currently if we try to add a group with space to any object, it will fails with error "Group was not found". This fixes the same.
RHBZ: https://bugzilla.redhat.com/1982058
=> ovirt_permission: fix group search that has space in it's name

changelogs/fragments/324-engine_setup-wait-for-engine-config-reboot.yml, roles/engine_setup/tasks/engine_setup.yml
Issue: when immediately after engine_setup someone tries to access the web server it is not available because it is starting
=> engine_setup: wait after engine-config reboot

changelogs/fragments/321-hosted_engine_setup-update-ansible-requirements-in-readme.yml, roles/hosted_engine_setup/README.md
Following a change in ovirt-hosted-engine-setup [1]
and addressing https://github.com/oVirt/ovirt-ansible-collection/issues/240
[1] https://gerrit.ovirt.org/#/c/ovirt-hosted-engine-setup/+/115113/1/ovirt-hosted-engine-setup.spec.in
=> roles: hosted_engine_setup: update Ansible requirements

README.md, changelogs/fragments/326-readme-update-ansible-requirements.yml, ovirt-ansible-collection.spec.in
=> Update Ansible requirement

changelogs/fragments/332-ovirt_auth-fix-token-no_log.yml, plugins/module_utils/ovirt.py, plugins/modules/ovirt_auth.py
Issue: when passing the already preheated token the ansible filters the value even for other tasks so the auth immediately fails.
=> ovirt_auth: fix token no_log

changelogs/fragments/340-replace-gluster-module-to-cli.yml, roles/cluster_upgrade/tasks/upgrade.yml
Replacing gluster module to CLI to support RHV automation hub
=> Replacing gluster module to CLI to support RHV automation hub

changelogs/fragments/348-ovirt_vm-add-virtio_scsi_enabled-and-multi_queues_enabled.yml, plugins/modules/ovirt_vm.py
https://bugzilla.redhat.com/show_bug.cgi?id=2004852
=> ovirt_vm: add virtio_scsi_enabled and multi_queues_enabled

changelogs/fragments/346-repositories-replace-redhat_subscription-and-rhsm_repository-with-command.yml, roles/repositories/tasks/rh-subscription.yml, roles/repositories/tasks/search-pool-id.yml
The downstream ansible execution environment does not contain any community collection.
(The `redhat_subscription` and `rhsm_repository` are in the community collections)
We need to switch to some other solution from the modules to make it compatible with the execution environment.
=> replace redhat_subscription and rhsm_repository with command

changelogs/fragments/371-ovirt_host-fix-failed_state_after_reinstall-condition.yml, plugins/modules/ovirt_host.py
failed_state_after_reinstall uses the host, so if the host was missing it automatically failed
=> ovirt_host: fix failed_state_after_reinstall condition

changelogs/fragments/371-ovirt_vm-add-virtio_scsi_multi_queues.yml, plugins/modules/ovirt_vm.py
Add virtio_scsi_multi_queues parameter to ovirt_vm as part of:
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1973251
Requires review from: @mnecas  @ahadas @liranr23
=> add virtio_scsi_multi_queues parameter to ovirt_vm

changelogs/fragments/381-engine_setup-honor-ovirt_engine_setup_offline.yaml, roles/engine_setup/tasks/main.yml
Honor ovirt_engine_setup_offline and
don't try installing any engine packages if in
offline mode.
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
=> engine_setup: skip pkg install in offline mode

changelogs/fragments/352-ovirt_remove_stale_lun-Retry-Multipath-f-while-removing-the-luns.yml, roles/remove_stale_lun/tasks/remove_mpath_device.yml
There are possiblities that the vdsm might be holding the LUN
temporarily while we run "multipath -f". In these cases, the flushing
fails with error "map in use". Retry multipath -f (6 * 5 seconds) to
workaround this race condition.
RHBZ: https://bugzilla.redhat.com/2023224
=> ovirt_remove_stale_lun: Retry "multipath -f" while removing the LUNs

changelogs/fragments/351-ovirt_remove_stale_lun-allow-user-to-remove-multiple-luns.yml, roles/remove_stale_lun/README.md, roles/remove_stale_lun/examples/remove_stale_lun.yml, roles/remove_stale_lun/tasks/remove_mpath_device.yml
Currently, if a user has to remove multiple LUNs, they have to run
the playbook individually for each LUNs. This is not that user
friendly if the user has to remove many LUNs. This commit provides
option to pass multiple LUNs.
=> Backport: ovirt_remove_stale_lun: Allow user to remove multiple LUNs (#357)

changelogs/fragments/352-ovirt_remove_stale_lun-Retry-Multipath-f-while-removing-the-luns.yml, roles/remove_stale_lun/tasks/remove_mpath_device.yml
There are possiblities that the vdsm might be holding the LUN
temporarily while we run "multipath -f". In these cases, the flushing
fails with error "map in use". Retry multipath -f (6 * 5 seconds) to
workaround this race condition.
=> Backport: ovirt_remove_stale_lun: Retry "multipath -f" while removing the LUNs

changelogs/fragments/390-ovirt_remove_stale_lun-Use-add_host-instead-of-delegate_to.yml, roles/remove_stale_lun/examples/remove_stale_lun.yml, roles/remove_stale_lun/tasks/fetch_hosts.yml, roles/remove_stale_lun/tasks/main.yml, roles/remove_stale_lun/tasks/remove_mpath_device.yml
As of now, we are using delegate_to using with_items to run the tasks in multiple hosts. This has got several problems:
- Ansible considers tasks for all the hosts as single task since we are iterating over host_info using with_items to run it on multiple hosts. So if any of the tasks fails in any of the hosts, it stops the execution of the subsequent tasks on all other hosts. For example, if multipath -f fails on any hosts, it won't run the task for removing the SCSI device even for the hosts where it was able to remove the device from multipath successfully.
- Each task is executed serially on the discovered hosts in DC because with_items unpacks serially.
- It's very difficult to understand which host it got failed, and "PLAY RECAP" is not useful.
Using add_host automatically solves …
=> ovirt_remove_stale_lun: Use add_host instead of delegate_to

changelogs/fragments/397-he_engine_abrt_configuration.yaml, roles/hosted_engine_setup/tasks/initial_clean.yml
Our abrt configuration is not being used on latest versions since we started
using 'systemd-coredump'.
because of that we should Restore initial abrt config files only when
they exist (on older versions).
=> roles: hosted_engine_setup: check if abrt config files exists on HE deploy

.github/workflows/build.yaml
Fetch the whole git history for the build so build job can verify if
changelog is required.
Fixes: #405 
=> Fetch the whole git history for the build

changelogs/fragments/409-hosted_engine_setup-Adjust-files-permissions.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/02_create_local_vm.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
Adjusting files permissions for supporting umask 077.
For security purposes we decided to use 770/660 permissions for the localvm directory, this directory contains the appliance image, and for creating the engine VM we must have its user/group configured for `qemu`, otherwise `qemu` user won't have search permissions for the appliance image (see also https://libvirt.org/drvqemu.html#posix-users-groups).
Therefore we have decided to use `qemu` group instead of `kvm`.
Bug-Url: https://bugzilla.redhat.com/2020620
=> roles: hosted_engine_setup: Adjust files permissions

.github/workflows/build.yaml
In accord to GitHub migration documentation [1] we should generate
DNF repository metadata for the built RPMs, so the artifact archive
can be used with OST.
[1] https://www.ovirt.org/develop/developer-guide/migrating_to_github.html
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>
=> workflows: Create DNF repo metadata for artifacts

automation/build.sh
Fixes ImportError exceptioin when using rich >= 11.0.0 in ansible-lint:
https://github.com/ansible-community/ansible-lint/issues/1795
=> Fixes rich dependency issue in ansible-lint

changelogs/fragments/396-info-modules-add-follow-link-url.yml, plugins/doc_fragments/ovirt_info.py, plugins/modules/ovirt_affinity_label_info.py, plugins/modules/ovirt_api_info.py, plugins/modules/ovirt_cluster_info.py, plugins/modules/ovirt_datacenter_info.py, plugins/modules/ovirt_disk_info.py, plugins/modules/ovirt_event_info.py, plugins/modules/ovirt_external_provider_info.py, plugins/modules/ovirt_group_info.py, plugins/modules/ovirt_host_info.py, plugins/modules/ovirt_host_storage_info.py, plugins/modules/ovirt_network_info.py, plugins/modules/ovirt_nic_info.py, plugins/modules/ovirt_permission_info.py, plugins/modules/ovirt_quota_info.py, plugins/modules/ovirt_scheduling_policy_info.py, plugins/modules/ovirt_snapshot_info.py, plugins/modules/ovirt_storage_domain_info.py, plugins/modules/ovirt_storage_template_info.py, plugins/modules/ovirt_storage_vm_info.py, plugins/modules/ovirt_system_option_info.py, plugins/modules/ovirt_tag_info.py, plugins/modules/ovirt_template_info.py, plugins/modules/ovirt_user_info.py, plugins/modules/ovirt_vm_info.py, plugins/modules/ovirt_vm_os_info.py, plugins/modules/ovirt_vmpool_info.py, plugins/modules/ovirt_vnic_profile_info.py
Add to each info module proper api-model links summary address.
Example for ovirt_vm_info:
All follow parameters can be found at following url: https://ovirt.github.io/ovirt-engine-api-model/master/#types/vm/links_summary
=> Add follow link url to api model links_summary

changelogs/fragments/415-cluster_upgrade-progress.yml, roles/cluster_upgrade/README.md, roles/cluster_upgrade/tasks/cluster_policy.yml, roles/cluster_upgrade/tasks/log_progress.yml, roles/cluster_upgrade/tasks/main.yml, roles/cluster_upgrade/tasks/upgrade.yml
Since cluster upgrade is a very long running process, adding progress tracking allows users and admins to easily track status.  Progress tracking is done by posting well formatted events.
Note: `roles/cluster_upgrade/tasks/upgrade.yml` was converted to a block.  This allows calculating var the tasks for a host upgrade needs without using `set_fact` style global facts.  The only annoyance is having to put them at the bottom of the file below all of the tasks.
Bug-Url: https://bugzilla.redhat.com/2040474
Signed-off-by: Scott J Dickerson <sdickers@redhat.com>
=> roles: cluster_upgrade: Add progress tracking/reporting

changelogs/fragments/359-he-replace-virt_net-and-xml-with-commands.yml, plugins/filter/ovirtvmip.py, roles/hosted_engine_setup/tasks/alter_libvirt_default_net_configuration.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml, roles/hosted_engine_setup/templates/network-config.j2
We need to replace all community modules because ansible-core 2.11 does not include any community modules.
New filter:
This patch adds `get_bridge_xml_to_dict` which converts stdout from `virsh net-dumpxml default` to the dictionary which has all bridge information. Later it is passed to the new template and used to configure the network bridge.
New template:
`network-config.j2` contains the jinja template from which the XML network configuration will be created.
Now users can specify both `he_ipv6_subnet_prefix` and `he_ipv4_subnet_prefix` and will support both modes before users could specify only one mode.
=> roles: hosted_engine_setup: replace virt_net and xml with commands

changelogs/fragments/417-add-no_log-to-manage-vms-state-task.yml, roles/vm_infra/tasks/vm_state_present.yml
"Manage VMs state" task is disclosing sensitive datas into logs (cloud-init root_password)
=> Add no_log to Manage VMs state task

changelogs/fragments/430-repositories-fix-force-flag-on-subscription-manager.yml, roles/repositories/tasks/rh-subscription.yml
Issue: The force flag on subscription-manager was always present. It was just checking if the  `ovirt_repositories_force_register` was defined which was in default so it was always present.
=> repositories: fix force flag on subscription-manager

changelogs/fragments/438-hosted_engine_setup-replace-xml-module.yml, plugins/filter/get_ovf_disk_size.py, roles/hosted_engine_setup/tasks/create_storage_domain.yml
We need to replace community modules since they are not included in
ansible >= 2.11
Bug-Url: https://bugzilla.redhat.com/2022620
=> roles: hosted_engine_setup: Replace xml community module

changelogs/fragments/426-ovirt_hosted-engine_setup-support-disa-stig-profile.yml, roles/hosted_engine_setup/files/35-allow-ansible-for-vdsm.rules, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
DISA STIG profile uses fapolicyd that blocks ansible command execution as non-root
(see: https://bugzilla.redhat.com/show_bug.cgi?id=1903549)
Adding a rule to /etc/fapolicyd/rules.d to allow ansible command execution as `vdsm` user.
The rule will be removed once it's no longer required.
Bug-Url: https://bugzilla.redhat.com/2020620
=> roles: hosted_engine_setup: Support disa stig profile

changelogs/fragments/443-ovirt_hosted_engine_setup-use-cat-command.yml, roles/hosted_engine_setup/tasks/create_storage_domain.yml
We get "could not locate file in lookup:" error, probably because
lookups execute and are evaluated on the Ansible control machine
and not on the remote machine
=> roles: hosted_engine_setup: Use cat command instead of lookup

.github/workflows/build.yaml
The ansible-core is provided by default repos from el8stream we don't need to use epel.
=> Automation: Fix ansible build workflow

changelogs/fragments/454-repositories-fix-dnf-module-variable.yml, roles/repositories/tasks/satellite-subscription.yml
Use the proper variable in repositories to set dnf modules when using satellite
=> Repositories: fix dnf module variable

changelogs/fragments/453-replace-calls-to-psql-as-postgres-with-engine_psql.yml, roles/hosted_engine_setup/defaults/main.yml, roles/hosted_engine_setup/tasks/create_target_vm/02_engine_vm_configuration.yml, roles/hosted_engine_setup/tasks/restore_backup.yml
engine_psql.sh is a script provided by the engine to access its DB.
It does not su/sudo to postgres but uses the configured credentials.
Do this for FIPS support, where psql as postgres fails.
=> Replace calls to psql as postgres with engine_psql.sh

changelogs/fragments/449-cluster_upgrade-progress-log.yml, roles/cluster_upgrade/tasks/log_progress.yml, roles/cluster_upgrade/tasks/main.yml
When running against a ovirt 4.5 instance, use the new REST feature defined by [ovirt-engine-api-model PR 32](https://github.com/oVirt/ovirt-engine-api-model/pull/32) and [ovirt-engine PR 170](https://github.com/oVirt/ovirt-engine/pull/170) to report the progress by both logging events and pushing the progress to the cluster.
Bug-Url: https://bugzilla.redhat.com/2040474
=> cluster_upgrade: Directly log progress to the cluster

ovirt-ansible-collection.spec.in
Because of ansible-core 2.12 uses python38 we need to rebuild the imageio client for python38.
Related to https://github.com/oVirt/ovirt-imageio/pull/57
=> spec: add ovirt-imageio-python38-client requirement

changelogs/fragments/463-hosted_engine_setup-add-and-set-storage-format.yml, plugins/modules/ovirt_storage_domain.py, roles/hosted_engine_setup/tasks/create_storage_domain.yml
Allow passing storage_format as is allowed by the Python SDK.
Bug-Url: https://bugzilla.redhat.com/1932147
=> Add storage format

changelogs/fragments/474-cluster-update-log-progress-fix.yml, roles/cluster_upgrade/tasks/log_progress.yml
Fixes: #476
Two critical fixes:
- Due to REST api changes during the review cycles, the `upgrade_action`
needed to change from `update` to `update_progress`
- The "Update the upgrade progress on the cluster" task will only
work once we know the API version, we know the version is at least
ovirt 4.5 and the cluster upgrade action has been started.  Adjust
its `when` clause to reflect those requirements.
For reference:
- REST api for the cluster upgrade endpoint: http://ovirt.github.io/ovirt-engine-api-model/master/#services/cluster/methods/upgrade
- Valid `update_action` values: http://ovirt.github.io/ovirt-engine-api-model/master/#services/cluster/methods/upgrade
=> cluster_upgrade: fix upgrade progress log_progress task

ovirt-ansible-collection.spec.in
Since ansible-core 2.12.3 the package does not obsolete but conflicts with ansible<2.10 and because of this, the upgrade fails.
The solution for this is to add our obsolete. When doing an upgrade from now it will remove the ansible 2.9 and install ansible-core 2.12.
=> Obsolete ansible 2.9

changelogs/fragments/466-ovirt_vm-fix-creating-raw-vm-from-cow-template.yml, plugins/modules/ovirt_vm.py
On a FC storage domain, creating a RAW vm (disk_format: "raw") from a COW template with vm_infra role gives as result : "Cannot add VM. Disk configuration (RAW Sparse backup-None) is incompatible with the storage domain type." 
I could be wrong on diagnostic but this seems to be caused by the unset "sparse" option. This commit fix it on our infrastructure.
=> fix creating a RAW vm from a COW template

.github/workflows/build.yaml, changelogs/fragments/490-use-rstcheck-3.4.yml
3.5.0 emits this to stderr:
/usr/local/lib/python3.6/site-packages/rstcheck.py:51: FutureWarning:
Python versions prior 3.7 are deprecated. Please update your python
version.
TODO: Revert this once we upgrade to python 3.8 (or 3.9, or both) in
automation.
=> automation: Use rstcheck < 3.5.0

.github/workflows/build.yaml, changelogs/fragments/492-use-cryptography-older-than-37.yml
37.0.0 emits this to stderr:
/tmp/ansible-test-_0gulbli/ansible/parsing/vault/__init__.py:44:
CryptographyDeprecationWarning: Python 3.6 is no longer supported by
the Python core team. Therefore, support for it is deprecated in
cryptography and will be removed in a future release.
TODO: Revert this once we upgrade to python 3.8 (or 3.9, or both) in
automation.
=> automation: Use cryptography < 37.0.0

changelogs/fragments/498-require-detail-up.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
When checking, near the end of the deployment, if the engine is healthy,
do not only check that 'health' is 'good', but also that 'detail' is
'Up'.
We recently had a case in CI where due to some problem the engine took a
long time to start, timing out the monitoring in HA, causing it to stop
the VM, and 'detail' was 'Powering Down', but this went unnoticed,
causing things to fail much later. So, in such a case, fail early.
=> roles: hosted_engine_setup: Require 'detail: Up'

changelogs/fragments/501-fix-archive-ownership.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
with umask 0777 (default for DISA STIG) the archive is not readable
later when we try to copy it as vdsm user.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2089332
=> roles: hosted_engine_setup: fix archive ownership

changelogs/fragments/504-collect-final-logs.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
Collect logs also on failures in 03_hosted_engine_final_tasks.yml.
The logs are still only from the local VM's disk, not the target.
Pushing this patch because we had cases where 'Check OVF_STORE volume
status' timed out.
=> roles: hosted_engine_setup: final: Collect engine logs

changelogs/fragments/506-force-updating-ovf-store.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
Directly ask the engine to update the OVF store instead of just hoping
that it eventually does.
If this patch works, we might remove other code, such as
setting/restoring OvfUpdateIntervalInMinutes and related.
Related-To: https://bugzilla.redhat.com/2090638
=> roles: hosted_engine_setup: Force updating the OVF store

changelogs/fragments/509-fix-keycloak-activation.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/03_engine_initial_tasks.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/04_engine_final_tasks.yml
keycloak integration had two env keys for this, and recently unified
them. We used the one that was removed. So fix, to use the current one.
=> roles: hosted_engine_setup: Fix keycloak activation/checking

changelogs/fragments/506-force-updating-ovf-store.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
Reverts oVirt/ovirt-ansible-collection#506
it seems to be flaky, unfortunately. OST sometimes fails with
11:11:55 E [ INFO ] TASK [ovirt.ovirt.hosted_engine_setup : Force updating the OVF store]
11:11:55 E [ ERROR ] ovirtsdk4.Error: Fault reason is "Operation Failed". Fault detail is "[Cannot ${action} Storage. Storage Domain OVF data is currently being updated.]". HTTP response code is 409.
11:11:55 E [ ERROR ] fatal: [localhost]: FAILED! => {"changed": false, "msg": "Fault reason is "Operation Failed". Fault detail is "[Cannot ${action} Storage. Storage Domain OVF data is currently being updated.]". HTTP response code is 409."}
=> Revert "roles: hosted_engine_setup: Force updating the OVF store"

changelogs/fragments/503-fix-ansible-ModuleNotFoundError.yml, roles/disaster_recovery/files/fail_back.py, roles/disaster_recovery/files/fail_over.py, roles/disaster_recovery/files/generate_vars.py, roles/disaster_recovery/files/ovirt-dr, roles/disaster_recovery/files/validator.py
When executing any Disaster Recovery script, the following error is received:
```
[root@storage-ge-13 files]# ./ovirt-dr generate
Traceback (most recent call last):
File "./ovirt-dr", line 15, in <module>
import fail_back
File "/usr/share/ansible/collections/ansible_collections/redhat/rhv/roles/disaster_recovery/files/fail_back.py", line 14, in <module>
from ansible.module_utils.six.moves import input
ModuleNotFoundError: No module named 'ansible'
```
The reason for that is the following `import` statement: `from ansible.module_utils.six.moves import input`.
There is no need to use "`six`" library at all since Python2 is deprecated!
All "`import`"s of "`six`" module can be deleted now and the builtin Python3 "`input()`" function will be used instead.
Bug-Url: …
=> Fix "'ansible' ModuleNotFoundError" in Disaster Recovery scripts

changelogs/fragments/534-ovirt_storage_domain-fix-inaccessible-error.yml, plugins/modules/ovirt_storage_domain.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2084235
Now when running playbook like:
```yml
- ovirt.ovirt.ovirt_storage_domain:
name: Ble        #This name is used in the different data center
host: host_mixed_2
data_center: golden_env_mixed
nfs:
address: "{{nfs_server}}"
path: "{{nfs_path}}"
auth: "{{ovirt_auth}}"
```
It will throw exception from engine:
```
"msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot attach Storage. The relevant Storage Domain is inaccessible.\n-Please handle Storage Domain issues and retry the operation.]\". HTTP response code is 409."
```
=> ovirt_storage_domain: Fix error for inaccessible storage domain

changelogs/fragments/422-add-qos-and-disk_profle.yml, plugins/modules/ovirt_disk.py, plugins/modules/ovirt_disk_profile.py, plugins/modules/ovirt_qos.py
Summary
- Adds ovirt_qos module to create a new QoS entry
- Adds ovirt_disk_profile to create a new disk profile
- Updates ovirt_disk to allow you to define the disk_profile on creation or to update a disk that currently exists
Examples
```yaml
ovirt.ovirt.ovirt_qos:
auth: "{{ ovirt_auth }}"
name: "myqos"
data_center: "Default"
state: "present"
max_iops: "100"
max_throughput: "100"
type: "storage"
ovirt.ovirt.ovirt_disk_profile:
auth: "{{ ovirt_auth }}"
name: "mydisk"
data_center: "Default"
state: "present"
storage_domain: "mystoragedomain"
qos: "myqos"
ovirt.ovirt.ovirt_disk:
auth: "{{ ovirt_auth }}"
name: "mydisk"
profile: "myqos"
state: "present"
```
=> ovirt_qos, ovirt_disk_profile, ovirt_disk: Add modules to allow for creation and updating of disk_profiles

changelogs/fragments/539-ovirt_vm-add-volatile.yml, plugins/modules/ovirt_vm.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/174
=> ovirt_vm: add volatile

automation/build.sh
After https://github.com/oVirt/ovirt-ansible-collection/pull/280 we are using the latest ansible-lint which does have not yet finished lints, those lint are labeled as experimental. I have decided to remove these lints from our CI.
=> CI: ansible-lint add experimental to skip list

changelogs/fragments/542-ovirt_vm-check-graphical-protocol.yml, plugins/modules/ovirt_vm.py
Before this user needed to input the protocol when wanted to change any console params
but without protocol, it throws exception `    "msg": "'NoneType' object is not iterable"`
=> ovirt_vm: check if user inputed graphical protocol

automation/build.sh, changelogs/fragments/544-shutdown_env-align-with-ansible-lint-6.0.yml, roles/shutdown_env/tasks/main.yml
Bug-Url: https://bugzilla.redhat.com/2097333
=> roles: shutdown_env: Align role with ansible-lint-6.0

tests/sanity/ignore-2.13.txt
Fails with:
https://github.com/oVirt/ovirt-ansible-collection/issues/546
=> Skip validate-module for plugins/modules/ovirt_event.py

tests/sanity/ignore-2.13.txt
Reverts oVirt/ovirt-ansible-collection#547
=> Revert "Skip validate-module for plugins/modules/ovirt_event.py"

changelogs/fragments/553-repositories-move-check-fips.yml, roles/repositories/tasks/install-satellite-ca.yml, roles/repositories/tasks/main.yml
=> repositories: move check fips to satellite ca install

meta/execution-environment.yml, meta/requirements.yml
This is because of ipaddr which was moved from `ansible.netcommon` in version 3.0.0 to `ansible.utils` in version 2.6.0
=> Fix: requirements for galaxy

automation/build.sh
After https://github.com/oVirt/ovirt-ansible-collection/commit/4a04b7042edf85d2f0e8cf93190f2a71a7458f21 we use containers to run the `ansible-test` for all versions. We no longer need to use it for pure build of the rpms
=> CI: disable ansible-test for build

changelogs/fragments/557-fix-he-migration-to-systemd-coredump-hosts.yml, roles/hosted_engine_setup/tasks/initial_clean.yml
This PR adds proper handling of a situation where the HE is migrated
from a host that was using abrt to a host that's using systemd-coredump.
Bug-Url: https://bugzilla.redhat.com/2101481
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>
=> he: Handle migration to hosts that use systemd-coredump

changelogs/fragments/559-update-documentation-ovirt_disk-requires-extra_params-when-extending-disk-with-non-unique-name.yml, plugins/modules/ovirt_disk.py
If the disk is referenced by `name` and is attached to a VM, make sure to specify `vm_name` / `vm_id` to prevent extension of another disk that is not attached to the VM.
Bug-Url: https://bugzilla.redhat.com/2016638
=> Improving the "ovirt_disk" documentation for disk extend flow

changelogs/fragments/563-he-setup-configure-ovn-with-he-host-fqdn.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
The FQDN of the HE host is required in ovn-sbctl in order for OVN to
function after a fresh HE deploy.
Change-Id: I951f90a9bb035d52285a8c5800f4711aecf34ab6
Bug-Url: https://bugzilla.redhat.com/2107063
Signed-off-by: Eitan Raviv <eraviv@redhat.com>
=> he-setup: ovn should be configured with he_host_name

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/280-fix-ansible-lint-for-basic-roles.yml, changelogs/fragments/422-add-qos-and-disk_profle.yml, changelogs/fragments/483-repositories-add-rhsm_environment.yml, changelogs/fragments/531-ovirt_host-fix-host-wait.yml, changelogs/fragments/532-cluster_upgrade-fix-starting-up-pinned-vms.yml, changelogs/fragments/533_fix_cleanup.yml, changelogs/fragments/534-ovirt_storage_domain-fix-inaccessible-error.yml, changelogs/fragments/536-he-specify-fqcn.yml, changelogs/fragments/537-image_template-remove-static.yml, changelogs/fragments/538-ovirt_vm-add-reset.yml, changelogs/fragments/539-ovirt_vm-add-volatile.yml, changelogs/fragments/542-ovirt_vm-check-graphical-protocol.yml, changelogs/fragments/543-fix-ansible-lint-for_disaster_recovery.yml, changelogs/fragments/544-shutdown_env-align-with-ansible-lint-6.0.yml, changelogs/fragments/545-he-setup-align-with-ansible-lint-6.0.yml, changelogs/fragments/550-ovirt_snapshot-add-vm_id.yml, changelogs/fragments/551-ovirt_host-fix-restarted-wait-condition.yml, changelogs/fragments/553-repositories-move-check-fips.yml, changelogs/fragments/554-fix-ansible_lint-for-disaster_recovery-and-remove_stale_lun.yml, changelogs/fragments/557-fix-he-migration-to-systemd-coredump-hosts.yml, changelogs/fragments/559-update-documentation-ovirt_disk-requires-extra_params-when-extending-disk-with-non-unique-name.yml, changelogs/fragments/563-he-setup-configure-ovn-with-he-host-fqdn.yml, galaxy.yml, ovirt-ansible-collection.spec.in
v2.2.0
======
Minor Changes
-------------
- During he_setup, configure ovn with he_host_name for correct operation of ovn (https://github.com/oVirt/ovirt-ansible-collection/pull/563).
- Fix "ansible-lint" version 6.0.0 "yaml" violations for "disaster_recovery" role (https://github.com/oVirt/ovirt-ansible-collection/pull/543).
- Fix "ansible-lint" version 6.0.0 violations for "disaster_recovery" & "remove_stale_lun" roles (https://github.com/oVirt/ovirt-ansible-collection/pull/554).
- Fix ansible-lint for basic roles (https://github.com/oVirt/ovirt-ansible-collection/pull/280).
- Updating the documentation - "vm_name" / "vm_id" and/or disk "id" parameter(s) are required when extending disk with non-unique name (https://github.com/oVirt/ovirt-ansible-collection/pull/559).
- …
=> Release 2.2.0

changelogs/fragments/568-he-setup-configure-ovn-with-he-host-fqdn.yml, roles/hosted_engine_setup/README.md, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
The FQDN of the HE host is returned by the variable he_host_address
and not by he_host_name.
This commit fixes commit 7ed85c7862fdb0f7ed7e5f61c771e85dc1774bbb,
(change-id I951f90a9bb035d52285a8c5800f4711aecf34ab6).
Change-Id: I22d97c869ffd0e05be652eb59b11b5e05db24b21
Bug-Url: https://bugzilla.redhat.com/2107063
Signed-off-by: Eitan Raviv <eraviv@redhat.com>
=> he-setup: ovn should be configured with he_host_address

changelogs/fragments/569-heconf-permissions.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
- hosted_engine_setup: fix HE VM networking on recent CentOS Stream
- align hosted-engine.conf permissions to host-deploy
=> hosted_engine_setup: hosted-engine.conf permissions

.config/ansible-lint.yml, automation/build.sh, build.sh
Add .ansible-lint config to skip var-spacing,ignore-errors,var-naming and experimental tests
=> Add ansible-lint config

changelogs/fragments/573-hosted_engine_setup-fetch-hosted-engine-ha-version-by-rpm-command.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
Bug-Url: https://bugzilla.redhat.com/2114769
=> hosted_engine_setup: Detect hosted-engine-ha version using /usr/libexec/platform-python

changelogs/fragments/567-hosted_engine_setup-remove-host-based-on-name.yml, roles/hosted_engine_setup/tasks/restore_backup.yml, roles/hosted_engine_setup/tasks/restore_host_redeploy.yml
In restore, remove the host from DB based on the name
in addition to the UUID.
Using multiple hosts with the same name is not allowed anyway.
Bug-Url: https://bugzilla.redhat.com/2003515
=> roles: hosted_engine_setup: restore - remove host also based on name

changelogs/fragments/580-cluster_upgrade-skip-host-upgrades-without-anything-to-update.yml, plugins/modules/ovirt_host.py
Issue: When doing cluster_upgrade on the host without any updates the host upgrade is not started. This creates a problem because we are waiting for the `HOST_UPGRADE_FAILED` `HOST_UPGRADE_FINISHED` `HOST_UPGRADE_FINISHED_AND_WILL_BE_REBOOTED` events, if the upgrade is not started the events are not created so we are waiting for something that will never be there. By default from UI it should timeout after 60 min.
=> cluster_upgrade: skip host upgrades without anything to update

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/567-hosted_engine_setup-remove-host-based-on-name.yml, changelogs/fragments/580-cluster_upgrade-skip-host-upgrades-without-anything-to-update.yml, changelogs/fragments/581-hosted_engine_setup-fix-broken-link.yml, changelogs/fragments/582-repositories-fix-example-variable-names.yml, ovirt-ansible-collection.spec.in
v2.2.3
======
Minor Changes
-------------
- hosted_engine_setup - fix ovirt-provider-ovn-driver broken link (https://github.com/oVirt/ovirt-ansible-collection/pull/581).
Bugfixes
--------
- cluster_upgrade - skip host upgrades without anything to update (https://github.com/oVirt/ovirt-ansible-collection/pull/580).
- hosted_engine_setup - restore - remove host also based on name (https://github.com/oVirt/ovirt-ansible-collection/pull/567).
- repositories - Fix example variable names (https://github.com/oVirt/ovirt-ansible-collection/pull/582).
=> Release 2.2.3

.config/ansible-lint.yml
The new version of ansible-lint adds a few new checks this PR makes the errors just warnings and we can fix them in the future.
=> CI: Fix ansible-lint

changelogs/fragments/587-ovirt_host-honor-activate-and-reboot-params.yml, plugins/modules/ovirt_host.py
ovirt_host - Honor activate and reboot_after_installation when they are set to false with reinstalled host state
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/586
=> ovirt_host: reinstalled - honor activate and reboot_after_installation when false

changelogs/fragments/592-he-setup-static-ipv6.yml, roles/hosted_engine_setup/templates/ifcfg-eth0-static-ipv6.j2
Setting up a static ipv6 for a hosted engine VM is achieved by passing an ifcg script file to the VM. This file should contain the setting IPV6_AUTOCONF=no in order for nmcli to fully configure the connection as static.
Change-Id: Ib36e14d15382cbe543d001d1005aa7683e4d7848
Bug-Url: https://bugzilla.redhat.com/2125658
Signed-off-by: Eitan Raviv <eraviv@redhat.com>
=> he_setup: fix static ipv6 ifcfg setup

.config/ansible-lint.yml
Temporarily fixes the CI fails of the ansible-lint
=> CI: ansible-lint update warn_lists and skip_list

changelogs/fragments/597-ovirt_disk-add-read_only-param.yml, plugins/filter/ovirtvmip.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/593
The issue was that we were using the filter for the list on dict which returns the list of keys but not values.
=> Fix ovirtvmipsv4 when using attr

changelogs/fragments/576-repositories-rhv-4.4-sp1-is-supported-only-on-rhel-8.6-eus.yml, roles/repositories/defaults/main.yml, roles/repositories/tasks/rh-subscription.yml, roles/repositories/tasks/satellite-subscription.yml, roles/repositories/vars/engine_eus_4.4.yml, roles/repositories/vars/host_eus_4.4.yml, roles/repositories/vars/host_ppc_eus_4.4.yml
RHV 4.4 SP1 is supported only on RHEL 8.6 EUS, so we need to prevent
customers to use it on RHEL 8.7+
Bug-Url: https://bugzilla.redhat.com/2108985
=> repositories: RHV 4.4 SP1 is supported only on RHEL 8.6 EUS

changelogs/fragments/597-ovirt_disk-add-read_only-param.yml, plugins/modules/ovirt_disk.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/594 
Add read_only param for disk attachments
=> ovirt_disk: Add read_only param for disk attachments

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/361-ovirt_disk-fix-disk-attachment.yml, changelogs/fragments/576-repositories-rhv-4.4-sp1-is-supported-only-on-rhel-8.6-eus.yml, changelogs/fragments/587-ovirt_host-honor-activate-and-reboot-params.yml, changelogs/fragments/592-he-setup-static-ipv6.yml, changelogs/fragments/596-fix-ovirtvmipsv4-when-using-attr.yml, changelogs/fragments/597-ovirt_disk-add-read_only-param.yml, changelogs/fragments/603-add-filter-docs.yml, galaxy.yml, ovirt-ansible-collection.spec.in
v2.3.0
======
Minor Changes
-------------
- filters - Add documentation to all filters (https://github.com/oVirt/ovirt-ansible-collection/pull/603).
- ovirt_disk - Add read_only param for disk attachments (https://github.com/oVirt/ovirt-ansible-collection/pull/597).
- ovirt_disk - Fix disk attachment to VM (https://github.com/oVirt/ovirt-ansible-collection/pull/361).
Bugfixes
--------
- Fix ovirtvmipsv4 when using attribute (https://github.com/oVirt/ovirt-ansible-collection/pull/596).
- he-setup - fix static ipv6 ifcfg setup (https://github.com/oVirt/ovirt-ansible-collection/pull/592).
- ovirt_host - Honor activate and reboot_after_installation when they are set to false with reinstalled host state (https://github.com/oVirt/ovirt-ansible-collection/pull/587).
- repositories - RHV 4.4 SP1 …
=> Release 2.3.0

changelogs/fragments/607-filters-fix-ovirtvmipsv4-with-atribute-and-network.yml, plugins/filter/ovirtvmip.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/593#issuecomment-1279687954
Issue: When filtering the vms with atr and network the filter failed because we were checking list of ips insead of single ip
=> filters: Fix ovirtvmipsv4 with attribute and network

changelogs/fragments/609-filterip4-fix-filter-list.yml, plugins/filter/ovirtvmip.py
error:
```
10:42:15 TASK [wait-for-vm-ip : Wait for VM IP] *****************************************
10:42:17 fatal: [[](/)]: FAILED! => {"msg": "The conditional check 'vm_info.ovirt_vms | ovirt.ovirt.ovirtvmipv4 | length > 0' failed. The error was: Unexpected templating type error occurred on ({% if vm_info.ovirt_vms | ovirt.ovirt.ovirtvmipv4 | length > 0 %} True {% else %} False {% endif %}): object of type 'filter' has no len()"}
```
=> ovirtvmipsv4: Fix filter list

changelogs/fragments/623-ovirt_nic-add-network_filter_parameters.yml, plugins/modules/ovirt_nic.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/622
=> ovirt_nic: Add network_filter_parameters

.github/workflows/build.yaml
=> Use oVirt checkout action in CI

changelogs/fragments/637-cluster_upgrade-fix-the-engine_correlation_id-location.yml, roles/cluster_upgrade/defaults/main.yml, roles/cluster_upgrade/tasks/main.yml
Issue:
When there is `random` filter in the ansible defaults, and the value is not specified, it does not generate one random number per run but per each use of the unset variable.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2142601
=> cluster_upgrade: Fix the engine_correlation_id location

changelogs/fragments/653-info-modules-use-dynamic-name.yml, plugins/modules/ovirt_affinity_label_info.py, plugins/modules/ovirt_cluster_info.py, plugins/modules/ovirt_datacenter_info.py, plugins/modules/ovirt_disk_info.py, plugins/modules/ovirt_event_info.py, plugins/modules/ovirt_external_provider_info.py, plugins/modules/ovirt_group_info.py, plugins/modules/ovirt_host_info.py, plugins/modules/ovirt_host_storage_info.py, plugins/modules/ovirt_network_info.py, plugins/modules/ovirt_nic_info.py, plugins/modules/ovirt_permission_info.py, plugins/modules/ovirt_quota_info.py, plugins/modules/ovirt_scheduling_policy_info.py, plugins/modules/ovirt_snapshot_info.py, plugins/modules/ovirt_storage_domain_info.py, plugins/modules/ovirt_storage_template_info.py, plugins/modules/ovirt_storage_vm_info.py, plugins/modules/ovirt_system_option_info.py, plugins/modules/ovirt_tag_info.py, plugins/modules/ovirt_template_info.py, plugins/modules/ovirt_user_info.py, plugins/modules/ovirt_vm_info.py, plugins/modules/ovirt_vm_os_info.py, plugins/modules/ovirt_vmpool_info.py, plugins/modules/ovirt_vnic_profile_info.py
info modules: use @NAMESPACE@.@NAME@ instead of ovirt.ovirt for deprecation warning
=> info modules: use @NAMESPACE@.@NAME@ instead of ovirt.ovirt for deprecation warning

changelogs/fragments/653-info-modules-use-dynamic-name.yml, plugins/modules/ovirt_affinity_label_info.py, plugins/modules/ovirt_cluster_info.py, plugins/modules/ovirt_datacenter_info.py, plugins/modules/ovirt_disk_info.py, plugins/modules/ovirt_event_info.py, plugins/modules/ovirt_external_provider_info.py, plugins/modules/ovirt_group_info.py, plugins/modules/ovirt_host_info.py, plugins/modules/ovirt_host_storage_info.py, plugins/modules/ovirt_network_info.py, plugins/modules/ovirt_nic_info.py, plugins/modules/ovirt_permission_info.py, plugins/modules/ovirt_quota_info.py, plugins/modules/ovirt_scheduling_policy_info.py, plugins/modules/ovirt_snapshot_info.py, plugins/modules/ovirt_storage_domain_info.py, plugins/modules/ovirt_storage_template_info.py, plugins/modules/ovirt_storage_vm_info.py, plugins/modules/ovirt_system_option_info.py, plugins/modules/ovirt_tag_info.py, plugins/modules/ovirt_template_info.py, plugins/modules/ovirt_user_info.py, plugins/modules/ovirt_vm_info.py, plugins/modules/ovirt_vm_os_info.py, plugins/modules/ovirt_vmpool_info.py, plugins/modules/ovirt_vnic_profile_info.py
Backport of https://github.com/oVirt/ovirt-ansible-collection/pull/653
=> Backport: info modules: use @NAMESPACE@.@NAME@ instead of ovirt.ovirt for deprecation warning

changelogs/fragments/661-delete-also-the-bridge.yml, roles/hosted_engine_setup/tasks/alter_libvirt_default_net_configuration.yml
Recently CI CentOS Stream 9 fails on the following `virsh net-start default` saying that virbr0 already exists. Not sure why it's not deleted by `virsh net-destroy default` - perhaps that's a change in libvirt. Let's remove the bridge explicitly.
Signed-off-by: Yedidyah Bar David <didi@redhat.com>
=> roles: hosted_engine_setup: Delete also the bridge

changelogs/fragments/647-add-default_route-usage-to-the-ovirt_network-module.yml, plugins/modules/ovirt_network.py
Currently, it is possible to configure default_route usage through web-UI or API, but not through ansible.
=> Add default_route usage to the ovirt_network module

changelogs/fragments/663-replace-getargspec-with-getfullargspec.yml, plugins/module_utils/ovirt.py
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/659
The `getargspec` was supported in python 2 and removed in python 3.11.
The alternative is `getfullargspec`, which is in all python 3 versions.
=> Replace getargspec with getfullargspec

changelogs/fragments/663-replace-getargspec-with-getfullargspec.yml, plugins/module_utils/ovirt.py
* Replace getargspec with getfullargspec
* Add changelog
Co-authored-by: Martin Perina <mperina@redhat.com>
=> backport: Replace getargspec with getfullargspec (#663)

changelogs/fragments/667-wait-for-host-to-be-in-result-state.yml, plugins/modules/ovirt_host.py
* Wait for host to be in result state
Bug introduced in #580.
The update_available is false just after the upgrade, and
HOST_UPGRADE_FINISHED_AND_WILL_BE_REBOOTED is logged. But the host is
not yet rebooted, so we still need to wait for the status to be UP or
MAINTENANCE.
* Fix wait_condition on host upgrade
In #580 we introduced a check on update_available state of the host to
determine if the host upgrade finished when there were no updates
available for te host.
The downside of this is that when the update finishes, the
update_available flag is cleared, and ansible thinks the host upgrade is
complete and starts upgrading the next node. But the reboot is not
completed yet, so result_state != h.status.
The fix here is to save the …
=> backport: Wait for host to be in result state (#621)

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/653-info-modules-use-dynamic-name.yml, changelogs/fragments/663-replace-getargspec-with-getfullargspec.yml, changelogs/fragments/667-wait-for-host-to-be-in-result-state.yml, ovirt-ansible-collection.spec.in
v2.4.2
======
Bugfixes
--------
- info modules - Use dynamic collection name instead of ovirt.ovirt for deprecation warning (https://github.com/oVirt/ovirt-ansible-collection/pull/653).
- module_utils - replace `getargspec` with `getfullargspec` to support newer python 3.y versions (https://github.com/oVirt/ovirt-ansible-collection/pull/663).
- ovirt_host - Wait for host to be in result state during upgrade (https://github.com/oVirt/ovirt-ansible-collection/pull/667)
=> Release 2.4.2

.github/workflows/build.yaml, changelogs/fragments/677-remove-provision_docker-dependency.yml, roles/engine_setup/tests/containers-deploy.yml, roles/engine_setup/tests/requirements.yml
Issues:
- Downgrade ubuntu to 20.04 (there was an upgrade around new years to 22.04)
Latest ubuntu python version is 3.10 and the pip deps install fails with:
```
ERROR: Exception:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
status = run_func(*args)
File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
return func(self, options, args)
File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
to_install = resolver.get_installation_order(requirement_set)
File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
weights = get_topological_weights(
File …
```
=> Fix CI test

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/621-wait-for-host-to-be-in-result-state.yml, changelogs/fragments/647-add-default_route-usage-to-the-ovirt_network-module.yml, changelogs/fragments/653-info-modules-use-dynamic-name.yml, changelogs/fragments/661-delete-also-the-bridge.yml, changelogs/fragments/663-replace-getargspec-with-getfullargspec.yml, changelogs/fragments/664-debug-virt-install.yml, changelogs/fragments/664-log-local-vm-console.yml, changelogs/fragments/673-ovirt_host-add-refresh.yml, changelogs/fragments/677-remove-provision_docker-dependency.yml, galaxy.yml, ovirt-ansible-collection.spec.in
v3.1.0
======
Minor Changes
-------------
- ovirt_host - Add refreshed state (https://github.com/oVirt/ovirt-ansible-collection/pull/673).
- ovirt_network - Add default_route usage to the ovirt_network module (https://github.com/oVirt/ovirt-ansible-collection/pull/647).
Bugfixes
--------
- engine_setup - Remove provision_docker from tests (https://github.com/oVirt/ovirt-ansible-collection/pull/677).
- he-setup - Log the output sent to the serial console of the HostedEngineLocal VM to a file on the host, to allow diagnosing failures in that stage (https://github.com/oVirt/ovirt-ansible-collection/pull/664).
- he-setup - Run virt-install with options more suitable for debugging (https://github.com/oVirt/ovirt-ansible-collection/pull/664).
- he-setup - recently `virsh net-destroy default` …
=> Release 3.1.0

changelogs/fragments/682-hosted_engine_setup-fix-disk-copying-command.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
Issues:
1. Desired Engine Disk size for hosted engine VM is not reflected and always 38GB.
Fix:
1. Adding the -n flag to use the same flags used by vdsm to ensure that we get consistent results compatible with volumes created by vdsm. Vdsm now uses -n flag for all qemu-img convert calls "https://gerrit.ovirt.org/c/vdsm/+/109784". 
https://bugzilla.redhat.com/show_bug.cgi?id=1828888#c5
Signed-off-by: Saksham Srivastava saksham.sa.srivastava@oracle.com
=> roles: hosted_engine_setup: Adding the -n flag to qemu-img command

ovirt-ansible-collection.spec.in
The ansible-core 2.14 uses python3.11 on Centos 9 stream instead of the default system python3.9. We need to build the rpm to use the collection with the ansible-core 2.14, which forces the python library to python3.11 so the ansible can use the collection.
=> spec: Add python3.11 requirements

changelogs/fragments/701-fix-jmespath.yml, ovirt-ansible-collection.spec.in
hosted-engine-setup runs with platform-python and requires jmespath
=> we need python3-jmespath for ansible runs with platform python

.automation/build.sh, .github/workflows/build.yaml, changelogs/fragments/702-drop-netaddr2.yml, roles/hosted_engine_setup/hooks/after_setup/add_host_storage_domain.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/05_add_host.yml, roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml, roles/hosted_engine_setup/tasks/fetch_host_ip.yml
commit fd20e99066c34006f392409b96150b29d0968470 dropped python-netaddr
dependency, remove remaining usage of filters requiring it
=> drop remaining netaddr

changelogs/fragments/700-fix-directlun.yml, plugins/modules/ovirt_disk.py
The direct LUN doesn't have a disk profile and follow_link(self._connection, entity.disk_profile) will be None. So detaching the LUN will fail with error "'NoneType' object has no attribute 'name'".
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=2183112
=> ovirt_disk: Fix issue in detaching the direct LUN

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/696-drop-netaddr.yml, changelogs/fragments/700-fix-directlun.yml, changelogs/fragments/701-fix-jmespath.yml, changelogs/fragments/702-drop-netaddr2.yml, changelogs/fragments/704-drop-netaddr3.yml, changelogs/fragments/706-he-update-README.yml, changelogs/fragments/712-ovirt_quota-fix-storage-size-typecast.yml, ovirt-ansible-collection.spec.in
v3.1.3
======
Bugfixes
--------
- HE - add back dependency on python3-jmespath (https://github.com/oVirt/ovirt-ansible-collection/pull/701)
- HE - drop remaining filters using netaddr (https://github.com/oVirt/ovirt-ansible-collection/pull/702)
- HE - drop usage of ipaddr filters and remove dependency on python-netaddr (https://github.com/oVirt/ovirt-ansible-collection/pull/696)
- HE - fix ipv4 and ipv6 check after dropping netaddr (https://github.com/oVirt/ovirt-ansible-collection/pull/704)
- hosted_engine_setup -  Update README (https://github.com/oVirt/ovirt-ansible-collection/pull/706)
- ovirt_disk -  Fix issue in detaching the direct LUN (https://github.com/oVirt/ovirt-ansible-collection/pull/700)
- ovirt_quota - Convert storage size to integer …
=> Release 3.1.3

changelogs/fragments/705-support-boot-disk-resizing-renaming.yml, roles/vm_infra/README.md, roles/vm_infra/tasks/rename_resize_boot_disk.yml, roles/vm_infra/tasks/vm_state_present.yml
Renames the boot disk when the `boot_disk_name` variable is defined
within the profile or the VM properties. (The latter has precedence
over the former). The VM disk must have the bootable flag set.
By default, if `boot_disk_name` is defined, the VM name will be
prepended to the boot disk name so the final name would be:
`{{ vm_name }}_{{ boot_disk_name }}`
This behavior can be disabled by setting the variable
`boot_disk_use_vm_name_prefix` to `false`. In this case the
final name of the boot disk will be the value of `boot_disk_name`.
The boot disk can also be resized by defining the `boot_disk_size`
variable.
The value can contain a suffix that complies to the IEC 60027-2
standard (for example 10GiB, 1024MiB)
Signed-off-by: Miguel Martín <mmartinv@redhat.com>
=> Support boot disk renaming and resizing.

changelogs/fragments/721-enhancement-vm-storage-error-resume-behaviour.yml, plugins/modules/ovirt_vm.py
Usage:  choices=['auto_resume', 'leave_paused', 'kill']
=> enhancement: storage_error_resume_behaviour of ovirt vm

changelogs/fragments/723-ovirt_role-fix-administrative-condition.yml, plugins/modules/ovirt_role.py
When user set administrative to false the option was not set and API failed with 400.
=> ovirt_role: Fix administrative option when set to False

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, galaxy.yml, ovirt-ansible-collection.spec.in
v3.2.0
======
Minor Changes
-------------
- ovirt_vm - Add tpm_enabled by @mmartinv (https://github.com/oVirt/ovirt-ansible-collection/pull/722).
- storage_error_resume_behaviour - Support VM storage error resume behaviour "auto_resume", "kill", "leave_paused" by @hemak88 (https://github.com/oVirt/ovirt-ansible-collection/pull/721)
- vm_infra - Support boot disk renaming and resizing by @mmartinv (https://github.com/oVirt/ovirt-ansible-collection/pull/705)
Bugfixes
--------
- ovirt_role - Fix administrative option when set to False by @mnecas  (https://github.com/oVirt/ovirt-ansible-collection/pull/723).
=> Release 3.2.0

CHANGELOG.rst, build.sh, changelogs/changelog.yaml, changelogs/fragments/700-fix-directlun.yml, changelogs/fragments/712-ovirt_quota-fix-storage-size-typecast.yml, changelogs/fragments/723-ovirt_role-fix-administrative-condition.yml, ovirt-ansible-collection.spec.in
v2.4.3
======
Bugfixes
--------
- ovirt_disk - Fix issue in detaching the direct LUN (https://github.com/oVirt/ovirt-ansible-collection/pull/700).
- ovirt_quota - Convert storage size to integer (https://github.com/oVirt/ovirt-ansible-collection/pull/712).
- ovirt_role - Fix administrative option when set to False (https://github.com/oVirt/ovirt-ansible-collection/pull/723).
=> Release 2.4.3

changelogs/fragments/733-enable-image-template-version-name.yml, roles/image_template/README.md, roles/image_template/defaults/main.yml, roles/image_template/tasks/qcow2_image.yml
- image_template: allow to setup template version name
- image_template: allow to setup template OS and description
=> image_template: enable image template version name

changelogs/fragments/741-enable-and-start-postfix-service.yml, roles/hosted_engine_setup/tasks/bootstrap_local_vm/05_add_host.yml
Issue:
On the SHE host ovirt-ha-agent logs are filled with mail notification errors
Fix:
Add an ansible task to enable and start postfix service on SHE hosts
Testing Done:
Created local yml file to enable and start postfix service. Verified that tasks start the service.
Signed-off-by: ShubhaOracle <Shubha.kulkarni@oracle.com>
=> Issue: On the SHE host ovirt-ha-agent logs are filled with mail notification errors

plugins/modules/ovirt_disk.py
ovirt_disk update documentation of logical unit id from lun_id to id to allying with the code
Continuation of: https://github.com/oVirt/ovirt-ansible-collection/pull/736
=> ovirt_disk: Fix documentation of logical unit id

build.sh
This should fix the following CI error:
fatal: detected dubious ownership in repository at '/__w/ovirt-ansible-collection/ovirt-ansible-collection' To add an exception for this directory, call:
git config --global --add safe.directory /__w/ovirt-ansible-collection/ovirt-ansible-collection
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
=> build: add safe.directory to fix CI build
